### ISSUE TITLE
approle auth issue

### ISSUE THREAD

**Issue by tuananh** [argoproj-labs/argocd-vault-plugin#188]
i obtain role id and secret and save it to config file `argocd-vault-config.yaml`  like below

```
VAULT_ADDR: https://<vault addr>
AVP_TYPE: vault
AVP_AUTH_TYPE: approle
AVP_ROLE_ID: 1234
AVP_SECRET_ID: 1234
```

i also create `payload.json` with the following content

```json
{"role_id": "1234", "secret_id": "1234"}
```

```
curl \
--request POST \
--data @payload.json \
https://vault-url/v1/auth/approle/login
```
while the curl works and i was able to get the token, login and get the secret. vault-plugin doesn't

i used vault plugin to test like this: create an `example-secret.yaml` like below

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: example-annotation
  annotations:
    avp.kubernetes.io/path: "secret/apps/dev/service01/credential"
type: Opaque
data:
  username: <service01_key01>
  password: <service01_key02>
```

and test with the following command

```sh
cat example-secret.yaml | argocd-vault-plugin generate -c argocd-vault-config.yaml -
```

I'm getting the following error

```sh
Error: Error making API request.

URL: GET https://<vault-url>/v1/secret/apps/dev/service01/credential
Code: 403. Errors:

* 1 error occurred:
	* permission denied


Usage:
  argocd-vault-plugin generate <path> [flags]
```
