### ISSUE TITLE
Improve GCP path syntax

### ISSUE THREAD

**Issue by werne2j** [argoproj-labs/argocd-vault-plugin#240]
Today the way the GCP inline path works, you have to input the name of the secret twice. For example
`projects/MY-PROJECT/secrets/my-secret#my-secret`. We should streamline this to not have to double up on the secret name. 

#### Proposal:
```
kind: Secret
apiVersion: v1
metadata:
  name: secret
  annotations:
    avp.kubernetes.io/path: projects/MY_PROJECT
type: Opaque
data:
  password: <test-secret>
```
```
kind: Secret
apiVersion: v1
metadata:
  name: secret
type: Opaque
data:
  password: <path:projects/MY_PROJECT#test-secret>
```

#### Instead of 
```
kind: Secret
apiVersion: v1
metadata:
  name: secret
  annotations:
    avp.kubernetes.io/path: projects/MY_PROJECT/secrets/test-secret
type: Opaque
data:
  password: <test-secret>
```
```
kind: Secret
apiVersion: v1
metadata:
  name: secret
type: Opaque
data:
  password: <path:projects/MY_PROJECT/secrets/test-secret#test-secrets>
```

We could potentially leave `secrets` in the path to make parsing a little easier but that can be discussed.

This would also need to be backwards compatible. So we would want to accept both ways for now and deprecate the old way until we decide to remove support completely.
