### ISSUE TITLE
Insert secret based on secret value key

### ISSUE THREAD

**Issue by sidewinder12s** [argoproj-labs/argocd-vault-plugin#248]
**Is your feature request related to a problem? Please describe.**

Let's say you have a JSON block of key/values in a single AWS Secret Manager secret. 

```json
{
    "account_id":"123456",
    "account_name": "test-account"
}
```

Can/could the plugin allow you to retrieve this secret and then insert based on a selected key?

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-example
  annotations:
    avp.kubernetes.io/path: "some-path/secret"
    avp.kubernetes.io/secret-version: "AWSCURRENT"
    avp.kubernetes.io/secret-key: "account_name"
```

**Alternatives**

I thought we might be able to do this within a helm chart (dump secret into a helm value, then have a helper that'll break it up), but may make it a lot more complicated to understand.

**Additional context**

Secrets within AWS Secret Manager are not exactly cheap at scale, so I was hoping to stuff much more data into 1 or 2 secrets.
