### ISSUE TITLE
Manifest generation error

### ISSUE THREAD

**Issue by dargentieri** [argoproj-labs/argocd-vault-plugin#252]
Hi everybody,
I have followed the instruction on [How to Use HashiCorp Vault and Argo CD for GitOps on OpenShift](https://cloud.redhat.com/blog/how-to-use-hashicorp-vault-and-argo-cd-for-gitops-on-openshift) and [Solving ArgoCD Secret Management with the argocd-vault-plugint](https://itnext.io/argocd-secret-management-with-argocd-vault-plugin-539f104aff05)

The secret is:
`kind: Secret apiVersion: v1 metadata: name: argocd-vault-plugin-credentials namespace: argocd type: Opaque stringData: AVP_VAULT_ADDR: 'http://vault:8200' AVP_VAULT_TOKEN: 'root' AVP_TYPE: 'vault' AVP_AUTH_TYPE: 'token'`

Threre are all environment variables on argocd-repo-server, but I have the following error:

`rpc error: code = Unknown desc = Manifest generation error (cached): argocd-vault-plugin generate ./ failed exit status 1: (0x1682740,0xc0004ec6b0)Error: ToYAML: could not convert replaced template into : error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in '{"resources":["example-secret.yaml"]}' Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD) ToYAML: could not convert replaced template into : error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in '{"resources":["example-secret.yaml"]}'`

example-secret.yam is:

`kind: Secret apiVersion: v1 metadata: name: example-secret annotations: avp_path: "secret/data/vplugin/supersecret" type: Opaque stringData: username: <username> password: <password>`

Can anyone help me?

**Comment by jkayani** [comment]
Can you paste your YAML with the newlines and indentation included? It looks like it's just malformed and that's why the plugin can't determine the `kind` of the manifest.

Also if you're using a version of AVP >= 1.0 then the `avp_path` annotation changed to `avp.kubernetes.io/path`: https://argocd-vault-plugin.readthedocs.io/en/stable/0x-1x/

**Comment by dargentieri** [comment]
Hi @jkayani , thanks for the reply.

The version is v1.1.1 so I changed the string from avp_path to avp.kubernetes.io/path but I have the same error.

argocd-vault-plugin-credentials.yaml
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
    AVP_VAULT_ADDR: 'http://vault:8200'
    AVP_VAULT_TOKEN: 'root'
    AVP_TYPE: 'vault'
    AVP_AUTH_TYPE: 'token'
```

example-secret.yaml
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/vplugin/supersecret"
type: Opaque
stringData:
  username: <username>
  password: <password>
```

On argocd-repo-server.yaml
```yaml
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        args:
          - >-
            wget -O argocd-vault-plugin
            https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v1.1.1/argocd-vault-plugin_1.1.1_linux_amd64 &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
```

**Comment by werne2j** [comment]
@dargentieri try changing AVP_VAULT_ADDR to VAULT_ADDR - https://argocd-vault-plugin.readthedocs.io/en/stable/config/

**Comment by dargentieri** [comment]
Hi @werne2j  I have changed as you suggested the variable from AVP_VAULT_ADDR to VAULT_ADDR  so the new argocd-vault-plugin-credentials.yaml is:

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
    VAULT_ADDR: 'http://vault:8200'
    AVP_VAULT_TOKEN: 'root'
    AVP_TYPE: 'vault'
    AVP_AUTH_TYPE: 'token'
```
In pod argocd-repo-server, I can see VAULT ADDR:
```sh
argocd@argocd-repo-server-54757d75cf-bpg98:~$ printenv | grep VAULT_ADDR
VAULT_ADDR=http://vault:8200
```
However there is the same error 
`rpc error: code = Unknown desc = Manifest generation error (cached): argocd-vault-plugin generate ./ failed exit status 1: Error: could not read YAML files: [could not read YAML: kustomization.yaml from disk: error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in '{"resources":["example-secret.yaml"]}'] Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD) could not read YAML files: [could not read YAML: kustomization.yaml from disk: error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in '{"resources":["example-secret.yaml"]}']`

**Comment by werne2j** [comment]
Ohh.. I think I understand. You are using kustomize. In order to use kustomize, you will need to build first and then pass the tanks to
AVP. You can see an example here https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-kustomize

**Comment by dargentieri** [comment]
Thanks @werne2j. I have updated the config map argocd-cm.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |
    - name: argocd-vault-plugin-kustomize
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-plugin generate -"]
```
but now there is this error

`rpc error: code = Unknown desc = Manifest generation error (cached): config management plugin with name 'argocd-vault-plugin' is not supported`

**Comment by werne2j** [comment]
@dargentieri that is because you changed the name of the plugin to `argocd-vault-plugin-kustomize `. Whatever you name the plugin in the configMap is whatever you want to chose for your Argo CD Application. You can read about the custom plugin concept here https://argo-cd.readthedocs.io/en/release-1.8/user-guide/config-management-plugins/

**Comment by dargentieri** [comment]
Thanks @werne2j  for your support. Now I have renamed the plugin name on *argocd-cm.yaml*
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-plugin generate -"]
```

There was an error `unsupported authentication type` so I have changed *argocd-vault-plugin-credentials.yaml*
FROM
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
    VAULT_ADDR: 'http://vault:8200'
    AVP_VAULT_TOKEN: 'root'
    AVP_TYPE: 'vault'
    AVP_AUTH_TYPE: 'token'
```
TO
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
    AVP_K8S_ROLE: vplugin
    AVP_TYPE: vault
    VAULT_ADDR: 'http://vault:8200'
    AVP_AUTH_TYPE: k8s
```
There was a last error,a synchronization error, because it was asked to set the namespace of the secret, so I changed the secret:
*example-secret.yaml*
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  namespace: default
  annotations:
    avp.kubernetes.io/path: "secret/data/vplugin/supersecret"
type: Opaque
stringData:
  username: <username>
  password: <password>
```

Now everything is ok!

PS: Why can't I use the other authentication method with AVP_AUTH_TYPE: 'token'?
