### ISSUE TITLE
remove-missing annotation doesn't work

### ISSUE THREAD

**Issue by 0m1xa** [argoproj-labs/argocd-vault-plugin#261]
**Describe the bug**
I'm expecting to delete keys with missing values.

**To Reproduce**
1. Get the example manifest with one or more keys with missing values.
```
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/remove-missing: true
    avp.kubernetes.io/path: "avp/data/test"
type: Opaque
stringData:
  password: <sample>
  password2: <sample2>
```
sample2 doesn't exist in Vault
2. Execute argocd-vault-plugin generate in terminal
3. See the same manifest as before generation.

**Expected behavior**
Generated manifest without keys with missing values

**Additional context**
argocd-vault-plugin v1.6.0 (947668d260d7e630b3dbc7d9dadfc4ed0650ccd3) BuildDate: 2021-12-01T21:37:22Z

**Comment by jkayani** [comment]
@0m1xa I think it has to be a string, so to force it as a string, try wrapping `true` in quotes like this:

```
apiVersion: v1
data: {}
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/remove-missing: "true"
  name: example-secret
type: Opaque
```
