### ISSUE TITLE
Can i use multiple approle for multiple vault namespaces ?

### ISSUE THREAD

**Issue by davshafik** [argoproj-labs/argocd-vault-plugin#284]
i am using approle as a backend and created argocd-vault-plugin-credentials secret  containing the following 
AVP_AUTH_TYPE : ...
AVP_ROLE_ID : ... 
AVP_SECRET_ID: ....
AVP_TYPE: .... 
VAULT_ADDR: ....

but this only works with single vault namespace . my question is 
is there a way to add multiple approle config for different namespaces of vault ?

**Comment by jkayani** [comment]
This should help: https://github.com/argoproj-labs/argocd-vault-plugin/issues/230#issuecomment-964252718. The idea is you set the AVP_ env vars in the Application spec so that you can set them on an app by app basis depending on which Vault namespace that app needs its secrets from

**Comment by werne2j** [comment]
Another possibility is to have a secret per credentials you want to use and then setup individual configManagementPlugins to use the different secrets. 
```
configManagementPlugins: |-
    - name: argocd-vault-plugin-1
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./", "-s some-secret"]
    - name: argocd-vault-plugin-2
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./", "-s some-other-secret"]
```
