### ISSUE TITLE
Cannot find secret even though it's in the same namespace and has access

### ISSUE THREAD

**Issue by TheAnachronism** [argoproj-labs/argocd-vault-plugin#301]
**Describe the bug**
I have the plugin setup and have the vault configuration in a secret. This secret is called 'argocd-vault-plugin-credentials' and it exists in the same namespace as argocd. First I had the issue, that the argocd-repo-server didn't have access to the secret, but I solved that by using the argo-server serviceAccount. (I don't know how good practice that is, but it was the easiest solution instead of creating a new SA). Now if I want to use the plugin with the command that is run buy the repo-server `helm template . | argocd-vault-plugin generate - --secret-name argocd-vault-plugin-credentials`, I get the following error: `Error: secrets "argocd" not found`

**To Reproduce**
1. Setup argocd with kustomize with the 2.2.5 install manfest as base resource and install argocd-vault-plugin with the correct deployment customizations and secrets
2. Try to use the plugin (either manual or with argocd sync)

**Expected behavior**
With the command, I described above it should generate the entire helm data with the replaceholders replaced by the values from vault. 

**Screenshots**
This is the result inside the argocd-repo-server
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/32616088/154718300-fe949f8a-30a3-431c-9303-903fb0ccde06.png">

**Comment by werne2j** [comment]
What version of AVP are you using?

**Comment by TheAnachronism** [comment]
```
argocd@argocd-repo-server-5db8b45bcc-5r5mh:~$ argocd-vault-plugin version
argocd-vault-plugin v1.9.0 (305e9905cb8592df08ebe42ffbc44361c0a9bfc6) BuildDate: 2022-02-15T13:51:51Z
```

**Comment by werne2j** [comment]
And can you post the yamls with the placeholders?

**Comment by TheAnachronism** [comment]
This is the helm template for a secret which has the placeholder

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "XXX.fullname" . }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.XXX.secretPath | quote }}
    avp.kubernetes.io/kv-version: "2"
type: Opaque
data:
  Token: {{ "<token>" | b64enc}}
```
And this is an entry in the values.yaml of that chart which defines at which location the secret is:
```
XXX:
  secretPath: "XXX/data/credentials"
```
