### ISSUE TITLE
Vault-plugin-support with helm chart with literal vaules

### ISSUE THREAD

**Issue by gouravjoshicldcvr** [argoproj-labs/argocd-vault-plugin#304]
While creating of ArgoCd application we can select with plugin or helm chart and if we select helm then how can we pass vault plugin. and if we select vault-plugin then how can we pass literal-values which we generally pass in application with helm chart.

Need a way where we can select both vault plugin and helm chart at a time.

**Comment by werne2j** [comment]
Hi @gouravjoshicldcvr we have documentation here https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-helm on how to use AVP with Helm.

You would add a new plugin like this:
```
configManagementPlugins: |
  - name: argocd-vault-plugin-helm
    init:
      command: [sh, -c]
      args: ["helm dependency build"]
    generate:
      command: ["sh", "-c"]
      args: ["helm template $ARGOCD_APP_NAME ${helm_args} . | argocd-vault-plugin generate -"]
```
Then use `plugin` in your Argo CD Application, selecting the one you created like above, and then point the repository to a Helm Chart in Git.
