### ISSUE TITLE
Support for all keys in a path as a secret

### ISSUE THREAD

**Issue by roee-hershko** [argoproj-labs/argocd-vault-plugin#305]
in my current setup we have a vault path for every service, so developers can add secrets in vault and those will be in injected automatically to there service.

i wonder if i can do something like that ? 
```
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "path/to/secret"
type: Opaque
dataString:
<range $key, $value := .>
 <$key>: <$value>
<end>
```
