### ISSUE TITLE
GCP Workload Identity support

### ISSUE THREAD

**Issue by rozdestvenskiy** [argoproj-labs/argocd-vault-plugin#306]
**Is your feature request related to a problem? Please describe.**
My team is trying to implement AVP to our project. But it's very uncomfortable and insecure to use JSON credentials for GCP service accounts. I was trying to configure using custom service account with workload identity annotation, but after creation AVP secret, I still get 
`ComparisonError     rpc error: code = Unknown desc = authentication required`
**Describe the solution you'd like**
Is it possible to use workload identity now with default or custom service account? Or are you planning to add this option?

---
Here is my configuration for service account:
````
apiVersion: v1`
  kind: ServiceAccount
  metadata:
  name: argocd-vault-sa
  namespace: "argocd"
  annotations:
    iam.gke.io/gcp-service-account: "my-sa@my-project.iam.gserviceaccount.com"
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
````

Here is spec for argocd-repo-server deployment:
````
spec:
  template:
    spec:
      serviceAccount: argocd-vault-sa
      automountServiceAccountToken: false
````

**Comment by loxley** [comment]
We use workload identity and have not had any issues with AVP.

**Comment by rozdestvenskiy** [comment]
> 

Can you share your configuration of k8s service account?

**Comment by loxley** [comment]
argocd-repo-server SA:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: repo-server
  annotations:
    iam.gke.io/gcp-service-account: some-sa@some-project.iam.gserviceaccount.com
  name: argocd-repo-server
  namespace: argocd
```
Then you need to create add a iam policy binding back to the kubernetes SA from the google SA:

```sh
$ gcloud iam service-accounts get-iam-policy some-sa@some-project.iam.gserviceaccount.com
bindings:
- members:
  - serviceAccount:some-workload-identity.svc.id.goog[argocd/argocd-repo-server]
  role: roles/iam.workloadIdentityUser
etag: BwXXIk3t6xQ=
version: 1
```
