### ISSUE TITLE
Activating Plugin in App of Apps pattern throws error

### ISSUE THREAD

**Issue by wofr** [argoproj-labs/argocd-vault-plugin#321]
**Describe the bug**
I try to use the plugin togehter with the App of Apps pattern.  Thererfore I activate the plugin in the "master" app but this does throw an exception in argocd.

`rpc error: code = Unknown desc = `argocd-vault-plugin generate ./` failed exit status 1: Error: could not read YAML/JSON files: could not read file: Chart.yaml from disk: error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in '{"apiVersion":"v2","appVersion":"1.0","description":"All applications of the BASF Scott Demo","name":"applications-scott","type":"application","version":"0.1.0"}' could not read file: templates/argo-rollout.yaml from disk: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.spec.destination.cluster":interface {}(nil)} could not read file: values.yaml from disk: error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in '{"spec":{"destination":{"cluster":"https://34.91.227.175","server":"https://kubernetes.default.svc"},"neo4jSecret":"neo4j-secret","source":{"repoURL":"git@git.atosone.com:atos-scott-pcf/scott-infrastructure-apps-services.git","targetRevision":"HEAD"}}}' Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>`

As soon as I remove the plugin from the "Master" App the exception goes away

The plugin it-self is corretly setup as using the plugin within secrets I created works fine.

**To Reproduce**

This is how my my App of Apps looks like this

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  # namespace of the argo-cd server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    path: applications/apps
    repoURL: git@............apps-services.git
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
      
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
```
it links to a Helm repo where I one of the apps I want to install looks like this. I dow want the plugin to subsitute the password for the installation. Within this helm repo I would like to install two applications (on of them should use the feature of the plugin to substitue the password).  

**Screenshot**
 
![grafik](https://user-images.githubusercontent.com/2195242/158984243-ea3d1965-6828-4161-9abd-930884b598a9.png)

**Expected behavior**

Plugin activation should not throw this exception
