### ISSUE TITLE
{{.Release.Namespace}} value translation when using AVP

### ISSUE THREAD

**Issue by ixxeL2097** [argoproj-labs/argocd-vault-plugin#323]
**Describe the bug**
When using plugin AVP with ArgoCD, the native value `{{.Release.Namespace}}` from helm chart is interpreted as the target namespace of the CR `Application` (namespace `argocd`) instead of the actual target namespace of the application itself (which can be whatever you want: `default`, `kube-system`, `test`...)

**Expected behavior**
 The native value `{{.Release.Namespace}}` from helm chart should be interpreted correctly and reflect the target namespace of the actual deployment instead of the CR `Application` of argocd's app.

Maybe i missed something about the AVP usage that could help me interpreting this variable as expected, but for now, this is a probleme for me since `{{.Release.Namespace}}` is always translated as `argocd` namespace no matter the real namespace I am deploying the app in.

Does anybody has a solution for this ? or is it an actual bug from the plugin ?

EDIT:

The only way I found to bypass this behaviour is to pass a plugin env value like this :
```bash
argocd app create [...] --plugin-env="helm_args=--namespace <app-target-namespace>"
```

with the template of configuration :
```yaml
      - name: vault-avp-helm-args
        init:
          command: [sh, -c]
          args: ["helm dependency build"]
        generate:
          command: ["sh", "-c"]
          args: ["helm template $ARGOCD_APP_NAME ${helm_args} . | argocd-vault-plugin generate -"]
```
