### ISSUE TITLE
[Feature/Help] usage with/despite validations in helm chart

### ISSUE THREAD

**Issue by herzogf** [argoproj-labs/argocd-vault-plugin#332]
**Is your feature request related to a problem? Please describe.**
We want to deploy helm charts containing validation (either via a [values.schema.json](https://helm.sh/docs/topics/charts/#schema-files) file or validation within the templates) with ArgoCD and the argocd-vault-plugin by using argocd-vault-plugin placeholders in the values.yaml files.
Some of those validation patterns in one of the helm charts (by an external vendor) don't allow the characters '<>' and thus the argocd-vault-plugin placeholder pattern breaks the validation in the "helm template" command.

We set up the vault plugin for helm in ArgoCD [as described in the documentation](https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-helm), i.e. first helm template is executed and then the argocd-vault-plugin. This leads to helm template failing because the validation for the vault placeholders in the values.yaml fails.

**Describe the solution you'd like**
At the moment we changed the plugin config in ArgoCD to first execute the argocd-vault-plugin command for all values yaml files and then feeding its output to helm template (see "additional context" at the end of this description for a sample config management plugin entry to do this). This works but looks extremly nasty and is not "the officially documented way" to use this plugin with ArgoCD + helm.

Thus we want to discuss this situation / problem with the community to perhaps come up with better solutions than our "hack" :-) Does anybody know a better way to use the vault plugin with restrictive helm value validation?

**Describe alternatives you've considered**
We looked at the following workarounds:

- Relax the validation in the helm charts to e.g. allow "<>" -> this is not always possible for charts not built in-house
- Disable validation within helm ("helm template" does not have any such option - perhaps we'd have to automatically manipulate the helm charts after the initial "helm dependency update")
- Use argocd-vault-plugin only for the values.yaml files and feed this to "helm template" (i.e. reverse the call order)

**Additional context**
For the last workaround (i.e. apply the argocd-vault-plugin to the values.yaml files first and then use this for helm template) we used the following configManagement plugin snippet for the argocd-cm:
```
  configManagementPlugins: |
    - name: argocd-vault-plugin-helm-vaultfirst
      init:
        command: [sh, -c]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["echo \"$helm_args\" | sed 's/-f //g' | xargs cat | sed 's/^/  /g' | (echo -e 'apiVersion: fakeWrapperResourceV1\nkind: FakeWrapper\nmetadata:\n  name: fake-k8s-object\nspec:' && cat) | argocd-vault-plugin generate -s 'my-secret-with-vault-connection-details' - | tail -n +6 | grep -v -e '^---$' | cut -c 3- | helm template $ARGOCD_APP_NAME -f - ."]
      lockRepo: true
```
This configManagement plugin wraps the values.yaml content within a fake k8s resource because argocd-vault-plugin cannot process "any yaml" but only accepts k8s objects/resources. After calling the vault plugin we then strip away the added k8s resource overhead and feed the resulting yaml to helm template.
(We use the helm_args variable only to specify the values.yaml files to use, e.g. "-f firstValuesFile.yaml -f secondValuesFile.yaml". The "-f" is not needed by this configManagementPlugin above but we kept the format to stay compatible with our non-hacked / original helm argocd-vault-plugin config)
