### ISSUE TITLE
Support for helm parameters (key:value) for imageupdater support

### ISSUE THREAD

**Issue by ricardojdsilva87** [argoproj-labs/argocd-vault-plugin#333]
Hello,

Regarding these issue already fixed:
https://github.com/argoproj-labs/argocd-vault-plugin/issues/304
https://github.com/argoproj-labs/argocd-vault-plugin/pull/309

Where a values.yaml file can be used with literal values instead of using the helm arguments.
I was wondering if there is any kind of way of using the parameters option like in an helm deployment. When specifying an helm deployment chart the values.yaml paramenters are loaded into the arrgocd UI. That enables the argocd imageupdater to update those values from the Application spec yaml.

````
project: project1
source:
  repoURL: 'repo URL'
  path: path
  targetRevision: main
  helm:
    valueFiles:
      - values.yaml
    parameters:
      - name: image.tag
        value: v1
        forceString: true
      - name: image.repository
        value: repo/image
      - name: image.credentials
        value: <path:secret-name#password>
    values: 'ingress: testurl.com'
destination:
  server: 'https://mycluster.com'
  namespace: test
syncPolicy: {}
```` 
Something similar to the above would replace the whole yaml under:
````
source:
  repoURL: repo
  targetRevision: 1.0.0
  plugin:
    name: test
    env:
      - name: HELM_VALUES
        value: |
            image.tag=v1
            image.repository=repo/image
            image.credentials=<path:secret-name#password>
````
If you need any more information or examples please ask.
Thanks!
