### ISSUE TITLE
Get all keys and values under specific vault path 

### ISSUE THREAD

**Issue by theJaxon** [argoproj-labs/argocd-vault-plugin#334]
I'm using the annotation `avp.kubernetes.io/path: "path/to/secret"` 
However I'll be using all the keys and values under that secret anyway so there's no need for me to go to the `stringData:` section and start filling what keys I'll need from that path so I'm trying to avoid having to fill this block each time 
```yaml
stringData:
  username: <username>
  password: <pass>
```

is it possible to allow this to happen via an additional annotation that will offer filling all the key values under specific secret path ?

**Comment by jkayani** [comment]
I'm afraid not - there was a previous PR to introduce this functionality https://github.com/argoproj-labs/argocd-vault-plugin/pull/281 but it was decided not to go in this direction

**Comment by bdoublet91** [comment]
Same usecase here.

Workaround with nested json dict like:
kv/data/test#list with secret:
```json
{
  "list": {
        "TEST": "TOTO",
        "TEST2": "TITI"
  }
}
```

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: toto
    helm.sh/chart: toto-1.0.1
  name: release-name-toto-env
stringData:
  TEST: TOTO
  TEST2: TITI
type: Opaque
```
I need to pass all env file stored in vault to a deployment with secretref.

Only bad thing in vault UI, I have to edit a json instead of the UI list

<img width="1477" height="259" alt="Image" src="https://github.com/user-attachments/assets/ec282b37-ba18-43dc-bd3e-287a386c78c5" />
