### ISSUE TITLE
generate [[glob] [...]] instead of [path]

### ISSUE THREAD

**Issue by sspreitzer** [argoproj-labs/argocd-vault-plugin#336]
This feature request is to solve the problem of paths with mixed content, which fails the `argocd-vault-plugin generate` command. Some content may not be Kubernetes manifests and thus leading the command to fail.

A solution could be to accept a list of globs instead of a single path. Eg:
```shell
argocd-vault-plugin './**/*{.yml,.yaml,.json}'
```

Right now this can probably achieved with (untested):
```shell
/bin/bash -O globstar -c 'cat ./**./*.yml | argocd-vault-plugin generate -'
```

For reference, there is a Golang glob implementation available; https://pkg.go.dev/github.com/gobwas/glob

**Comment by sspreitzer** [comment]
Atm. we use this:
```yaml
            configManagementPlugins: |
              - name: argocd-vault-plugin-helm
                init:
                  command: ['bash', '-c']
                  args: ["helm dependency build"]
                generate:
                  command: ['bash', '-c']
                  args: ['helm template ${HELM_RELEASE_NAME:-${ARGOCD_APP_NAME}} . --values <(echo "${HELM_VALUES}") --include-crds ${HELM_ARGS} | argocd-vault-plugin generate -']
              - name: argocd-vault-plugin
                generate:
                  command: ['bash', '-c']
                  args: ['find ${DIRECTORY:-.} ${FINDOPTS:--regextype egrep -iregex ''.*\.(yml|yaml|json)''} -printf ''---\n'' -exec cat {} \; | argocd-vault-plugin generate -']
```

Due to unkown reason, yaml single quote escaping does not work properly and the ENV variable hast to be supplied as:
(This config excludes directories and files that start with a dot, pattern `./.*`)
```yaml
  plugin:
    name: argocd-vault-plugin
    env:
      - name: FINDOPTS
        value: -regextype egrep -iregex .*\.(yml|yaml|json) -and -not -iregex ^\./\..*$
```
