### ISSUE TITLE
How to scope AVP configuration per ArgoCD project for multitenancy usage

### ISSUE THREAD

**Issue by MrLuje** [argoproj-labs/argocd-vault-plugin#338]
**Is your feature request related to a problem? Please describe.**
We are using ArgoCD so multiple teams can manage their deployments.
ArgoCD is setup by ops, so are ArgoCD projects and teams can create & manage their own applications in namespaces defined by projects.
Vault is setup in the same way : a secret engine per team, with appropriate policies

I was reading the docs about [AVP in a multitenancy environment](https://argocd-vault-plugin.readthedocs.io/en/stable/config/#using-kubernetes-secrets-for-supplying-avp-configuration). If I follow the example about `foo-team-aws-sm-credentials` and `bar-team-aws-sm-credentials` and also make use of specifying the AVP secret in a given namespace, I can have these secret in team's namespace like :
- foo-team:aws-sm-credentials
- bar-team:aws-sm-credentials

So AVP secrets are properly stored in teams' namespace and teams just have to specify which secret to use in applications, like :
```yaml
      env:
        - name: AVP_SECRET
          value: foo-team:aws-sm-credentials
```
But from what I understand, there is nothing preventing anyone from **bar-team** to use `foo-team:aws-sm-credentials`.
I agree they won't have access to the AVP_SECRET itself if RBAC setup properly, but they will be able to pull secrets from the other team's **secret engine**

**Describe the solution you'd like**
Some proposals, not sure if they are doable with today ArgoCD architecture & plugin model :
- have some way to restrict which AVP_SECRET can be used by ArgoCD projects
- have some way to restrict a `configManagementPlugins` by ArgoCD projects and teams juste specify the plugin name to use

**Describe alternatives you've considered**
- One ArgoCD per team but not the best solution
- [Vault Agent Injector](https://www.vaultproject.io/docs/platform/k8s/injector) but I prefer the idea to keep using regular k8s secrets 

**Additional context**
I may have missed another way to manage a multitenant ArgoCD & Vault, so I'm open  to any other solutions

**Comment by HumairAK** [comment]
> This would be something the operator of Argo CD for your team/org to figure out. Limit permissions so no one outside of team A can not even see team A credentials or deploy to team A's namespace. and also scope the actual secrets in your secret manager so that no one outside of team A could login and see team A secrets.

I might be missing something. But even if Team B members couldn't see Team A's creds or deploy to their namespace, what's stopping Team B from using argocd to create secrets by specifying $AVP_SECRET as `team-a:aws-sm-credentials` and accessing Team A's secrets from the secret backend?

**Comment by werne2j** [comment]
@HumairAK you would use a service account that doesn’t have permission to access anything outside of the namespace team B is working in. So it couldn’t read the secret from team As namespace.

**Comment by werne2j** [comment]
In the case of HashiCorp Vault you could follow this pattern:
https://argocd-vault-plugin.readthedocs.io/en/stable/config/#passing-avp-configuration-as-environment-variables-in-the-app-manifest. 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://team-a-repo'
    targetRevision: HEAD
    path: apps/git/nginx/manifests
    plugin:
      name: vault-avp
      env:
        - name: VAULT_NAMESPACE
          value: team-a-namespace
```

Where you are setting namespace in the Argo CD application CR in a way that the individual teams don't have access to that. Then when trying to do something like the secret described vault would only lookup in the namespace that that particular team should have access to.

These are only suggestion, and it is really up to the user to decide what pattern works best for them based on how Kubernetes, Argo CD and AVP work.

**Comment by HumairAK** [comment]
>  vault would only lookup in the namespace that that particular team should have access to.

Is this assuming team-a / team-b in this scenario cannot themselves deploy argocd applications? 

For example, if team-a/team-b have access to create argocd applications, then they can get around this by changing: 
```
    plugin:
      name: vault-avp
      env:
        - name: VAULT_NAMESPACE
          value: team-a-namespace   # just change to team-b-namespace?
```

Right?
