### ISSUE TITLE
is invalid: spec.template.spec.containers[0].image: Required value_

### ISSUE THREAD

**Issue by fedeam** [argoproj-labs/argocd-vault-plugin#339]
**Describe the bug**
I have the following error when trying to patch the deployment "repo-server. [According to the documentation](https://argocd-vault-plugin.readthedocs.io/en/stable/installation/)

_The Deployment "argo-cd-argocd-repo-server" is invalid: spec.template.spec.containers[0].image: Required value_

**To Reproduce**

same steps as the documentation: Installing in Argo CD
step:  _The first technique is to use an init container and a volumeMount to copy a different version of a tool into the repo-server container._

**Expected behavior**
install the plugin

**Additional context**
  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argo-cd"
  version    = "4.5.7" #HA 
  Kubernetes EKS = 1.22

**Comment by fedeam** [comment]
I try to apply this

$ kubectl patch deployment argo-cd-argocd-repo-server -n argocd --patch-file /PATH/deploy-argocd-repo-server.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-cd-argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argo-cd-argocd-repo-server
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-plugin
          subPath: argocd-vault-plugin
        envFrom:
          - secretRef:
              name: argocd-vault-plugin-credentials
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        env:
          - name: AVP_VERSION
            value: "1.7.0"
        args:
          - >-
            wget -O argocd-vault-plugin
            https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
      automountServiceAccountToken: true
```
