### ISSUE TITLE
AVP looks for kubernetes secret in argocd namespace, and not the namespace specified

### ISSUE THREAD

**Issue by justin-obn** [argoproj-labs/argocd-vault-plugin#341]
**Describe the bug**
I have all my argocd resources installed in my `cicd` namespace. 
When I run `argocd-vault-plugin generate`, the error shows it's looking for the secret in the `argocd` namespace, whereas I deployed the secret and every other thing to `cicd` namespace

**To Reproduce**
1. I have a `Kustomization.yaml` file that builds everything for me
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.7/manifests/install.yaml
  - ingress-internal.yaml
  - avp-config-qa.yaml

patchesStrategicMerge:
  - patches/clusterrolebinding.yaml
  - patches/deployments.yaml
  - patches/cm.yaml
  - patches/cm-secret.yaml
  # - patches/sa.yaml

images:
  - name: quay.io/argoproj/argocd
    newName: 117521xxxxxx.dkr.ecr.us-east-1.amazonaws.com/fuji-argocd
    newTag: 2.1.7-0.1.0
```
In that file, I have built my own `CUSTOM IMAGE` as per [https://argocd-vault-plugin.readthedocs.io/en/stable/installation/](installation), and using it in my kubernetes deployment

2. I also set `automountServiceAccountToken` to `true` as per your documentations through `patches/deployments.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      automountServiceAccountToken: true
```

3. I see all my kubernetes resources are going to the `cicd` namespace

4. I then `exec` into the `argocd-repo-server` in my `cicd` namespace and try to use the plugin,  like such
 ```
$ argocd-vault-plugin generate - -s avp-config-qa
   
  kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/wcs/apps/console-api-dev"
type: Opaque
data:
  password: <k2Secret>
```

5. I receive
```
Error: secrets "avp-config-qa" is forbidden: User "system:serviceaccount:cicd:default" cannot get resource "secrets" in API group "" in the namespace "argocd"
Usage:
  argocd-vault-plugin generate <path> [flags]

```
My secret and every other thing is in the `cicd` namespace

**Expected behavior**
The `YAML` is outputted to stdout with `<k2Secret>` substituted with the value from vault

**Code Snippets**
**argocd-repo-server**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
  name: argocd-repo-server
  namespace: cicd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
.....truncated........
      automountServiceAccountToken: true
.....truncated........
        image: 117521322591.dkr.ecr.us-east-1.amazonaws.com/fuji-argocd:2.1.7-0.1.0
.....truncated........
```

**avp-config-qa**
```
apiVersion: v1
kind: Secret
metadata:
  name: avp-config-qa
  namespace: cicd
stringData:
.....truncated........
type: Opaque
```
**Versions**
```
$ argocd-vault-plugin version
argocd-vault-plugin v1.11.0 (4133295001e037b917a8884da84af42f12a51cae) BuildDate: 2022-04-26T13:54:32Z
```

```
kubectl version --short=true
Client Version: v1.22.5
Server Version: v1.21.5-eks-bc4871b
```

**EDIT**
This was initially tried using ArgoCD
```
---
apiVersion: v1
data:
  configManagementPlugins: |
    - name: avp-helm-qa
      generate:
        command: ["bash", "-c"]
        args: ['helm template "$ARGOCD_APP_NAME" -f <(echo "$HELM_VALUES") . | argocd-vault-plugin generate - -s ${AVP_SECRET}']
  dex.config: |
.....truncated........
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: cicd
---

```

<img width="1290" alt="Screenshot 2022-05-05 at 11 58 39" src="https://user-images.githubusercontent.com/74918572/166892561-0cfea8bb-5414-4fe6-9b86-c9267d50d45d.png">

After I got the error from ArgoCD UI, I tried through the argocd repo server directly
