### ISSUE TITLE
When using the app of app pattern and helm build, Chart.yaml is missing

### ISSUE THREAD

**Issue by codex70** [argoproj-labs/argocd-vault-plugin#347]
**Describe the bug**
When using an app of app patterns pointing to a git hub repository for the helm chart, I get an error saying Chart.yaml is missing.

**To Reproduce**
Following the instructions here:
https://argocd-vault-plugin.readthedocs.io/en/stable/installation/
and here:
https://argocd-vault-plugin.readthedocs.io/en/stable/usage/

Create an app of apps template `app-of-secrets.yaml` using a test repository from https://github.com/dmitrii-dmnk/argocd-vault-plugin-demo

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-secrets
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default

  source:
    path: apps/secrets
    repoURL: https://github.com/dmitrii-dmnk/argocd-vault-plugin-demo.git
    targetRevision: master

    plugin:
      name: argocd-vault-plugin-helm #argocd-vault-plugin
      env:
        - name: HELM_VALUES
          value: |
            # non-vault helm values are specified normally
            someValue: lasldkfjlksa
            moreStuff:
              - a
              - b
              - c
        - name: AVP_TYPE
          value: vault
        - name: AVP_AUTH_TYPE
          value: k8s
        - name: AVP_K8S_ROLE
          value: argocd-repo-server
        - name: VAULT_ADDR
          value: https://vault.vault:8200
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

and with any of the configurations from https://argocd-vault-plugin.readthedocs.io/en/stable/usage/, for example
```
configManagementPlugins: |
  - name: argocd-vault-plugin-helm
    generate:
      command: ["bash", "-c"]
      args: ['helm template "$ARGOCD_APP_NAME" -f <(echo "$HELM_VALUES") . | argocd-vault-plugin generate -']
```

I get the following (or similar) error:
```
rpc error: code = Unknown desc = Manifest generation error (cached): `bash -c helm template "$ARGOCD_APP_NAME" -f <(echo "$HELM_VALUES") . | argocd-vault-plugin generate -` failed exit status 1: Error: Chart.yaml file is missing Error: No manifests Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>
```

Interestingly, if I do not use helm, (so using the plugin from the installation page), I do not get the error:
```
data:
  configManagementPlugins: |-
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
```
**Expected behavior**
The application builds and deploys as expected

**Comment by codex70** [comment]
Hi @werne2j, I have a helm chart at `path: apps` following the normal process for ArgoCD. Without the plugin everything works as expected.

I then have an app of apps yaml file which looks like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: operations
  source:
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: AVP_TYPE
          value: vault
        - name: AVP_AUTH_TYPE
          value: k8s
        - name: AVP_K8S_ROLE
          value: argocd-repo-server
        - name: VAULT_ADDR
          value: https://vault.vault:8200
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"
    path: apps/
    repoURL: https://my-repo
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
Which works as expected.

If I then try to create another app:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-secrets
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default

  source:
    path: apps/secrets
    repoURL: https://github.com/dmitrii-dmnk/argocd-vault-plugin-demo.git
    targetRevision: master

    plugin:
      name: argocd-vault-plugin-helm #argocd-vault-plugin
      env:
        - name: HELM_VALUES
          value: |
            # non-vault helm values are specified normally
            someValue: lasldkfjlksa
            moreStuff:
              - a
              - b
              - c
        - name: AVP_TYPE
          value: vault
        - name: AVP_AUTH_TYPE
          value: k8s
        - name: AVP_K8S_ROLE
          value: argocd-repo-server
        - name: VAULT_ADDR
          value: https://vault.vault:8200
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
Then I get the issue with the helm chart. `Error: Chart.yaml file is missing`

What I really want to do is use secret values for HELM_VALUES in the individual yaml files for the applications. I can use vault secrets to create kubernetes secrets within the applications, but not in HELM_VALUES. This is necessary to pass things like passwords that normally are in the helm values file.

**Comment by codex70** [comment]
The directory structure would be:
```
- app
    - Chart.yaml
    - Values.yaml
    - templates
        - root.yaml
        - app-of-secrets.yaml
```
With the app-of-secrets requiring the secret helm values.

**Comment by codex70** [comment]
Thanks, that gives me an idea of something I could try. Do you have any examples of the second part of your comment: "instead use a plain avp config management plugin"

**Comment by werne2j** [comment]
This repo should help https://github.com/jkayani/avp-demo-kubecon-2021 but with that i mean to do 
```
data:
  configManagementPlugins: |-
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
```
with a directory of kubernetes resources
