### ISSUE TITLE
InvalidSpecError: Unable to generate manifests in .: rpc error: code

### ISSUE THREAD

**Issue by abhilaikhn** [argoproj-labs/argocd-vault-plugin#349]
Hi All,

I have deployed my ArgoCD application using existing Helm charts and I am trying to connect my ArgoCD with vault and following the instructions as mentioned. 

Below is my secret yaml 

`apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
type: Opaque
stringData:
  VAULT_ADDR: <MY_VAULT_ADDRESS>
  VAULT_TOKEN: <MY_VAULT_TOKEN>
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token`

However when I try to create the app ArgoCD error shows 

```
Unable to create application: application spec is invalid: 
InvalidSpecError: Unable to generate manifests in .: rpc error: code = Unknown desc = `argocd-vault-plugin generate ./` failed exit status 1: 
Error: Must provide a supported Vault Type Usage: argocd-vault-plugin generate <path> [flags] 
Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). 

The namespace can be overridden by using the format <namespace>:<name>
```
I tried methods suggested in below issue but it didnt helped.
#117 

Could someone please suggest what am I missing.

**Comment by jkayani** [comment]
- Make sure you're using the latest release https://github.com/argoproj-labs/argocd-vault-plugin/releases
- Make sure your config is set how you expect: exec into your `argocd-repo-server` pod and examine the set environment variables (I assume you're mounting the AVP config Secret's keys as env vars in the pod)

**Comment by nicolimo86** [comment]
I have the same exact issue.

I followed @jkayani hint and I connected to `argocd-repo-server` pod via:
`kubectl exec --stdin --tty argocd-repo-server-c797f89c5-bwm2v -- /bin/bash`
There was indeed some mess in my config, because I found those values:
```
Defaulted container "argocd-repo-server" out of: argocd-repo-server, download-tools (init), copyutil (init)
argocd@argocd-repo-server-659944dd7b-x4svn:~$ env
argocd-vault-plugin-config.yaml=apiVersion: v1
data:
  VAULT_ADDR: Zm9v
  AVP_AUTH_TYPE: Zm9v
  AVP_GITHUB_TOKEN: Zm9v
  AVP_TYPE: Zm9v
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
```
I updated the values in my manifest (argocd-vault-plugin-config.yaml ) using the correct values:
```
apiVersion: v1
data:
  VAULT_ADDR: https://myvault.domain.example.com
  VAULT_TOKEN: ***
  AVP_AUTH_TYPE: token
  AVP_TYPE: vault
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
```
I recreated the secret in the `argocd` namespace using:
`kubectl create secret generic argocd-vault-plugin-credentials --from-file=./argocd-vault-plugin-config.yaml -n argocd`

I restarted the `argocd-repo-server` deployment using:
`k rollout restart deployment/argocd-repo-server`

At this point I see the new values reflected in the `argocd-repo-server` pod, but I still have the same error when trying to create an argocd application.

Additional info: 
I installed the latest release of the `argocd-vault-plugin`.

**Comment by jkayani** [comment]
Try verifying that the Kubernetes secret values are base64 encoded correctly: https://github.com/argoproj-labs/argocd-vault-plugin/issues/301#issuecomment-1045181117

I also noticed this:

```
env
argocd-vault-plugin-config.yaml=
```

where it looks like you're setting an environment variable with the name `argocd-vault-plugin-config.yaml` and setting the YAML contents to it's value - if I read that right, that isn't going to work. Use one of the approaches outlined in the docs: https://argocd-vault-plugin.readthedocs.io/en/stable/config/

**Comment by abhilaikhn** [comment]
Thanks for the suggestion let me try these

**Comment by nicolimo86** [comment]
Thanks for the hints it finally works. The problem was indeed the creation of the secrets defined in `argocd-vault-plugin-config.yaml `. I had to change it like this (using `stringdata` instead of `data`):
```
apiVersion: v1
data:
  VAULT_ADDR: https://myvault.domain.example.com
  VAULT_TOKEN: ***
  AVP_AUTH_TYPE: token
  AVP_TYPE: vault
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
```
then recreate the secret like this: `kubectl apply -f argocd-vault-plugin-config.yaml`.
