### ISSUE TITLE
argocd-repo-server-deploy.yaml - Container name 

### ISSUE THREAD

**Issue by rcarre** [argoproj-labs/argocd-vault-plugin#351]
**Describe the bug**
Don't you think that container name in file **_argocd-repo-server-deploy.yaml_** should be **repo-server** instead of **argocd-repo-server** to ensure proper patchesStrategicMerge when templating is done from helm chart argo/argo-cd?

Please find here enclosed an extract from  command line **helm template argo/argo-cd --version 4.8.3** output 
```
---
# Source: argo-cd/templates/argocd-repo-server/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-argocd-repo-server
  labels:
    helm.sh/chart: argo-cd-4.8.3
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.3.4"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
      app.kubernetes.io/instance: release-name
  revisionHistoryLimit: 5
  replicas: 1
  template:
    metadata:
      labels:
        helm.sh/chart: argo-cd-4.8.3
        app.kubernetes.io/name: argocd-repo-server
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: repo-server
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/version: "v2.3.4"
    spec:
      containers:
      - name: repo-server
        image: quay.io/argoproj/argocd:v2.3.4
```
