### ISSUE TITLE
Support Key Value style secret in Google Secrets Manager

### ISSUE THREAD

**Issue by nickwei8** [argoproj-labs/argocd-vault-plugin#360]
**Is your feature request related to a problem? Please describe.**
I am trying to store and retrieve secrets in google secrets manager. 
Sometimes I like to put all settings in one secret, the secret will be key value pairs like below:
```
staging:
  db-password: staging-password
  host-name: staging.example.com
production:
  db-password: prod-password
  host-name: prod.example.com
```

**Describe the solution you'd like**
I like to be able to refer to the secret using `secrets['staging']['db-password']`.
Terraform have similar functionality https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/secret_manager_secret_version#attributes-reference

Not sure if it's already supported, can't find this in documentation. 
Please advise if this can be achieved somehow. 

Thanks,

Nick
