### ISSUE TITLE
[Question] Simplest way to inject secrets in static parts of a Helm chart

### ISSUE THREAD

**Issue by beyondbill** [argoproj-labs/argocd-vault-plugin#361]
I'm new to the plugin. The [usage doc](https://argocd-vault-plugin.readthedocs.io/en/stable/usage) seems indicate using Helm along with argocd-vault-plugin requires a [different registration](https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-helm)

```yaml
configManagementPlugins: |
  - name: argocd-vault-plugin-helm
    init:
      command: [sh, -c]
      args: ["helm dependency build"]
    generate:
      command: ["sh", "-c"]
      args: ["helm template $ARGOCD_APP_NAME . --install-crds | argocd-vault-plugin generate -"]
```

in argocd-cm than the [generic one](https://argocd-vault-plugin.readthedocs.io/en/stable/installation/)

```yaml
configManagementPlugins: |-
  - name: argocd-vault-plugin
    generate:
      command: ["argocd-vault-plugin"]
      args: ["generate", "./"]
```

What if I only want to inject secrets in static parts of a Helm chart? For example, no secret injection in any Helm values and the only injections are in a `secrets.yaml` (see below) in a Helm chart. Can I simply go with the [generic plugin registration](https://argocd-vault-plugin.readthedocs.io/en/stable/installation/)? I think it should work based on my understanding of the plugin but want to confirm with the community. Thanks!

```yaml
# secrets.yaml in a Helm chart
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "path/to/secret"
type: Opaque
data:
  password: <password-vault-key>
```

I also have a similar question for a `Kustomization`. Thanks again!

**Comment by jkayani** [comment]
```
configManagementPlugins: |
  - name: argocd-vault-plugin-helm
    init:
      command: [sh, -c]
      args: ["helm dependency build"]
    generate:
      command: ["sh", "-c"]
      args: ["helm template $ARGOCD_APP_NAME . --install-crds | argocd-vault-plugin generate -"]
```

is suggested in the docs because normally a Helm chart will include Helm-templated secret manifests, like:

```
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.Release }}-secret
  annotations:
    {{ .Values.commonAnnotations }}
type: Opaque
data:
  password: {{ .Values.password }}
```

which you'd need to render via Helm first so that your AVP placeholder `<password>` gets interpolated into the manifest which AVP can then recognize. Even if you're just bundling static YAMLs with your chart, if you want the rest of the charts resources (deployments, services, whatever else it creates) to be created as part of your Argo app, you should use the earlier mentioned plugin definition. If you just used the generic plugin registration, you might get an error with AVP trying to read the `Chart.yaml` and `values.yaml` (un-rendered Helm chart files) as Kubernetes manifests.

**Comment by beyondbill** [comment]
Thanks @jkayani !

> If you just used the generic plugin registration, you might get an error with AVP trying to read the Chart.yaml and values.yaml (un-rendered Helm chart files) as Kubernetes manifests.

For us, there's no AVP annotation in any yaml files other than `secrets.yaml`. Are they still under risk? 

>  if you want the rest of the charts resources (deployments, services, whatever else it creates) to be created as part of your Argo app, you should use the earlier mentioned plugin definition

Other than the risk of messing unintended Helm chart files, is there other potential risk of using the generic plugin registration? 

Our argocd applications are defined like this

```yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo
  namespace: argocd-server
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bar
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/donkey/scheduler
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
{{- with .Values.spec.helmValues.foo }}
{{ toYaml . | indent 8 }}
{{- end }}
```
where `.Values.spec.helmValues` is passed in from app-of-apps. As we do not intend to use AVP to inject secrets into any 
values, we are trying to avoid the complexity of handling that if possible. The question is whether it's possible and safe given our limited use cases.

**Comment by werne2j** [comment]
If you have ANY Helm templating at all, a Helm specific plugin is necessary. Since the custom plugin replaces Argo CDs mechanism for handling manifests, if you do not use the Helm plugin your other Helm files will fail to apply as they will not have been rendered.

**Comment by beyondbill** [comment]
@werne2j Wow I did not know that
> the custom plugin replaces Argo CDs mechanism for handling manifests

then, would `spec.helm.values` still be passed to the Helm release as in the following argocd application?

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo
  namespace: argocd-server
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bar
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/foo
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    plugin:
      name: argocd-vault-plugin-helm
    helm:
      values: |
{{- with .Values.spec.helmValues.foo }}
{{ toYaml . | indent 8 }}
{{- end }}
```

**Comment by werne2j** [comment]
> then, would spec.helm.values still be passed to the Helm release as in the following argocd application?

No it's not passed.

You would want to follow the guide here (https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-helm) on using Helm with AVP

**Comment by beyondbill** [comment]
@werne2j Thanks! I think I get it right this time

plugin registration
```yaml
configManagementPlugins: |
  - name: argocd-vault-plugin-helm
    generate:
      command: ["bash", "-c"]
      args: ['helm template "$ARGOCD_APP_NAME" -f <(echo "$ARGOCD_ENV_HELM_VALUES") . | argocd-vault-plugin generate -']
```

argocd application
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo
  namespace: argocd-server
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bar
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/foo
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: ARGOCD_ENV_HELM_VALUES
          value: |
{{- with .Values.spec.helmValues.foo }}
{{ toYaml . | indent 12 }}
{{- end }}
```
where `.Values.spec.helmValues` is passed from an app-of-apps, which itself does not use AVP plugin.
