### ISSUE TITLE
Plugin doesn't work with helm toJson function

### ISSUE THREAD

**Issue by Ingvin** [argoproj-labs/argocd-vault-plugin#367]
**Describe the bug**
Charts where variables are used in helm toJson function doesn't work with the plugin.
toJson change < and > symbols in strings to \u003c and \u003e so after `helm template` they are not replaced by plugin.

**To Reproduce**
1. Create values.yaml with:
```
csiConfig:
  - clusterID: "<path:secret/path#cluster-id>"
    monitors:
      - "v2:172.18.8.5:3300/0,v1:172.18.8.5:6789/0"
      - "v2:172.18.8.6:3300/0,v1:172.18.8.6:6789/0"
      - "v2:172.18.8.7:3300/0,v1:172.18.8.7:6789/0"
nodeplugin:
  podSecurityPolicy:
    enabled: true
provisioner:
  podSecurityPolicy:
    enabled: true
```
2. Run `helm template ceph-csi/ceph-csi-rbd -f cephrbd.yaml --include-crds | argocd-vault-plugin generate - | grep 'clusterID''` there will be string `"\u003cpath:secret/path#cluster-id\u003e"` instead of secret

**Expected behavior**

**Comment by RomanBats** [comment]
Not sure if this is a bug of a plugin.
The documentation states that if you use specific placeholders with <> braces they will be replaced with actual secrets.
You are not providing such placeholders, so why do you expect the plugin to replace anything?

**Comment by BMonsalvatge** [comment]
Having this same error #381 

> You are not providing such placeholders, so why do you expect the plugin to replace anything?

I think @Ingvin specified the clusterID with the secret in the example?

Additionally I am having the same error with the following definition:
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  annotations:
    avp.kubernetes.io/path: "secret/kv/test"
type: Opaque
data:
  my-data: <foo>
  ```

**Comment by BMonsalvatge** [comment]
I managed to solve my issue by including `plugin: {}` in my application manifest like so:

```yaml
project: myproject
source:
  repoURL: 'https://gitlab.com/test/test-repo.git'
  path: test
  targetRevision: HEAD
  plugin: {}
destination:
  server: 'https://kubernetes.default.svc'
  namespace: test
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```
