### ISSUE TITLE
[Feature request] Provide sub-manifests with resources for people who want to provide their own argocd

### ISSUE THREAD

**Issue by jskrzypek** [argoproj-labs/argocd-vault-plugin#369]
**Is your feature request related to a problem? Please describe.**
I want to consume AVP via the kustomize manifest but AVP's manifest already includes the argocd manifest. I am using a different version of argocd (v2.4.4 now, but imagine it were a fork of their manifest or something). The following kustomization does not work, because kustomize will complain that the avp generator tries to provide the same resource id:

```sh
➜ cat <<EOF > kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=v2.4.4
  - https://github.com/argoproj-labs/argocd-vault-plugin//manifests/cmp-sidecar?ref=9c7288a5b2d395fea19c1100f2cd07b547cc1ee2
EOF

➜ kustomize build .
Error: accumulating resources: accumulation err='accumulating resources from 'https://github.com/argoproj-labs/argocd-vault-plugin//manifests/cmp-sidecar?ref=9c7288a5b2d395fea19c1100f2cd07b547cc1ee2': URL is a git repository': recursed merging from path '/private/var/folders/yn/3qwz5t5j2_x__rdy__mpkf580000gn/T/kustomize-791362366/manifests/cmp-sidecar': may not add resource with an already registered id: ServiceAccount.v1.[noGrp]/argocd-application-controller.[noNs]
```

**Describe the solution you'd like**
If you provide the AVP specific resources/patches in a sub-manifest, then I would be able to point to that instead of the manifest that explicitly includes a reference to argocd, allowing me to provide my own. 

I.e. a folder structure like this:
```tree
manifests
├── cmp-configmap
│   └── kustomization.yaml                  # 1)
├── cmp-sidecar
│   └── kustomization.yaml                  # 2)
└── plugin
    ├── configmap
    │   ├── argocd-cm.yaml
    │   ├── argocd-repo-server-deploy.yaml
    │   └── kustomization.yaml              # 3) 
    └── sidecar
        ├── argocd-repo-server.yaml
        ├── cmp-plugin.yaml
        └── kustomization.yaml              # 4)
```

And the `kustomization.yaml`s as labeled:

1) manifests/cmp-configmap/kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-cd/manifests/cluster-install
- ../plugin/configmap

```

2) manifests/cmp-sidecar/kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Note: Versions below 2.4.0 will not always work if trying to use AVP with Helm
# Fixed in https://github.com/argoproj/argo-cd/pull/9319
resources:
- https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.4.0
- ../plugin/sidecar
```

3) manifests/plugin/configmap/kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- argocd-repo-server-deploy.yaml
- argocd-cm.yaml

```

4) manifests/plugin/sidecar/kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cmp-plugin.yaml

patchesStrategicMerge:
- argocd-repo-server.yaml
```

**Describe alternatives you've considered**
You could provide the current option, which has the problems I described. Another alternative would be to provide 4 separate and not-overlapping manifests for the 2 CMP strategies w/ and w/o argocd, but that's just inherently not DRY and doesn't seem to offer any advantages.

**Additional context**
I'll submit a PR with my suggested changes.
