### ISSUE TITLE
Helm  with SOPS doesn't work

### ISSUE THREAD

**Issue by innovia** [argoproj-labs/argocd-vault-plugin#375]
we have an encrypted values file for helm in a file called `secrets.yaml` 

we try to run this command as the plugin

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
    - name: argocd-vault-plugin-helm
      generate:
        command: ["sh", "-c"]
        args: ["helm template . | argocd-vault-plugin generate -"]
    # This lets you pass args to the Helm invocation as described here: https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-helm
    - name: argocd-vault-plugin-helm-with-args
      generate:
        command: ["sh", "-c"]
        args: ["helm template ${helm_args} . | argocd-vault-plugin generate -"]
    - name: argocd-vault-plugin-kustomize
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-plugin generate -"]
```

the problem is that helm creating base64 secrets with the encrypted strings

the command here is from the docs, but it first renders the template and only then passing it to the plugin for decryption which at this point its already base64 so it can not decrypt it after the fact

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: example
type: Opaque
data:
  token: ENC[AES256_GCM,data:bnl+E+iH7wJsf+qW2eVimeoS023SXhMq/Cz9g3A3XWg=,iv:+dFDOr3MCR5kbHXDnDxDa0AMaUevsNKJte6K+p+lEC0=,tag:AXewW53lQEOUxsJot50Jnw==,type:str]

```
