### ISSUE TITLE
Error on retrieving secrets with ArgoCD Vault plugin

### ISSUE THREAD

**Issue by aubreyphan** [argoproj-labs/argocd-vault-plugin#377]
**Describe the issue**

I have set up ArgoCD Vault plugin to be able to retrieve secret from Vault to deploy our cluster. However, I run into this error while referring to the secret values. 

> error validating data: [unknown object type "nil" in Secret.data.azurestorageaccountkey, unknown object type "nil" in Secret.data.azurestorageaccountname

My setup:

AKV version 1

values.yaml
```
    configManagementPlugins: |
      - name: argocd-vault-plugin
        generate:
          command: ["sh", "-c"]
          args: ["argocd-vault-plugin generate ./"]
      - name: argocd-vault-plugin-helm
        generate:
          command: ["bash", "-c"]
          args: ['helm template "$ARGOCD_APP_NAME" -f <(echo "$HELM_VALUES") . | argocd-vault-plugin generate -']
```

Defining helm values in the application manifest
```
    plugin:
      name: argocd-vault-plugin-helm
      env:
      - name: HELM_VALUES
        value: |
          azurestorageaccountname: <path:mypath/aks-base-runners-non-prod#storage_account_name>
          azurestorageaccountkey: <path:mypath/aks-base-runners-non-prod#storage_account_key>
```

Secret manifest
```
apiVersion: v1
kind: Secret
metadata:
  name: azurefile-secret
data:
  azurestorageaccountname: {{ .Values.azurestorageaccountname }}
  azurestorageaccountkey: {{ .Values.azurestorageaccountkey }}
type: Opaque
```

**Expected behavior**

Argocd plugin should be able to find secret in vault path and configure Kubernetes secret.
