### ISSUE TITLE
error found in #10 byte of ...|foo\u003e

### ISSUE THREAD

**Issue by BMonsalvatge** [argoproj-labs/argocd-vault-plugin#381]
**Describe the bug**
When trying to create a secret I get the following error when syncing/

`one or more objects failed to apply, reason: Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 0, error found in #10 byte of ...|foo\u003e"},"kind":"|..., bigger context ...|iVersion":"v1","data":{"my-data":"\u003cfoo\u003e"},"kind":"Secret","metadata":{"annotations":{"avp.|...`

**To Reproduce**
1. Create secret like so:
```yaml
# Using avp.kubernetes.io/path  Annotation
# We are setting avp.kubernetes.io/path  to tell the plugin exactly where to find data
# https://argocd-vault-plugin.readthedocs.io/en/stable/howitworks/#generic-placeholders
kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  annotations:
    avp.kubernetes.io/path: "secret/kv/test"
type: Opaque
data:
  my-data: <foo>
```
3. Make sure secret exist with value foo at path specified in annotation.

**Expected behavior**
I'd expect the secret to get created.

**If you've tried running `argocd-vault-plugin generate` with `--verbose-sensitive-output` to help debug, please include that output here after redacting any secrets.**

I am not sure exactly how this should be manually ran against this file?  Can I run it from the repo server with a temp file with the definition I posted above?

**Additional context**
Just worked through some other weird (mostly my fault) issues in #380
