### ISSUE TITLE
Unable to pull certificates/keys from AWS Secrets Manager

### ISSUE THREAD

**Issue by jeunii** [argoproj-labs/argocd-vault-plugin#382]
**Describe the bug**
I am trying to create a `kubernetes.io/tls` type secret in my k8s cluster. My secret manifest looks like

```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-tls-new
  annotations:
    avp.kubernetes.io/path: "dev/argocd"
data:
  tls.key: <ARGOCD_TLS_KEY>
  tls.crt: <ARGOCD_TLS_CERT>
type: kubernetes.io/tls
```

In AWS secret manager, under `dev/argocd` I have,

<img width="873" alt="Screen Shot 2022-07-27 at 3 54 28 PM" src="https://user-images.githubusercontent.com/46089687/181360421-15a1e0a6-2763-4e17-95fa-60bbf78cdbd6.png">

But in ArgoCD when I try to sync the secret, I get the error message

```
Secret in version "v1" cannot be handled as a Secret: v1.Secret.Data: decode base64: illegal base64 data at input byte 0, error found in #10 byte of ...|CATE-----","tls.key"|..., bigger context ...|EBpsr6GtPAQw4dy753ec5\\n-----END CERTIFICATE-----","tls.key":"-----BEGIN PRIVATE KEY-----\\nMIIEvwIB|...
```

All other types of secrets fetching works. but not when im trying to import certs/keys.

Is this a limitation of this plugin ?
