### ISSUE TITLE
Label values that happen to be a number with scientific notation are converted to a decimal number

### ISSUE THREAD

**Issue by ykoer** [argoproj-labs/argocd-vault-plugin#383]
**Describe the bug**
All of our resources are labeled with the 7-digits commit hash. If the commit hash happens to be a decimal number with a scientific notation (like e1, e2, etc), the ArgoCD Vault plugin converts that label to a decimal number without the e notation.

**To Reproduce**
1. Create following secret
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
  labels:
    commitId: 81111e1
  name: test-app
data:
  foo: bar
```
2. cat /tmp/secret.yaml  | /usr/local/bin/argocd-vault-plugin generate -
```
apiVersion: v1
data:
  foo: bar
kind: Secret
metadata:
  annotations: null
  labels:
    commitId: 811110
  name: test-app
```

Even though the risk of this happening is very low, it should be fixed.

Thanks
Yusuf
