### ISSUE TITLE
Path and Parameters no longer auto suggest in GUI after sidecar method setup.

### ISSUE THREAD

**Issue by BMonsalvatge** [argoproj-labs/argocd-vault-plugin#385]
**Describe the bug**
When creating a new app, or editing an existing one via the GUI, it's no longer showing the available parameters or suggest the helm repos to use when selecting a path within a repo.

**To Reproduce**
1. Go to create a new app
2. Click on select repo that has multiple repos
3. click on path
4. normally it should show a drop down with available options, but instead it just shows `.`

**Expected behavior**
Should show parameters available in the values.yaml and paths available within the selected repo.

**Screenshots/Verbose output**
![image](https://user-images.githubusercontent.com/1095871/184055607-fbd92aa6-5a21-4006-8a8b-4d7fa499acfa.png)

**Additional context**
My cmp-plugins are setup as follows:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true
      # Note: this command is run _before_ anything is done, therefore the logic is to check
      # if this looks like a Kustomize bundle
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate -"
      lockRepo: false
  avp-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      # Note: this command is run _before_ any Helm templating is done, therefore the logic is to check
      # if this looks like a Helm chart
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
      generate:
        command:
          - sh
          - "-c"
          - |
            helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . |
            argocd-vault-plugin generate -
      lockRepo: false
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "."
      lockRepo: false
---
```

**Comment by BMonsalvatge** [comment]
I tried going through the two sidecar methods specified here: https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/docs/usage.md with no success...

Additionally I am unable to specify the usage of a different values file other than values.yaml

With the following app manifest my app is still pulling the default `values.yaml`

```yaml
project: projectname
source:
  repoURL: 'https://myrepo'
  path: test
  targetRevision: HEAD
  plugin:
    name: argocd-vault-plugin-helm
    env:
      - name: helm_args
         value: -f qa.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: test-qa
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```

**Comment by Tizull** [comment]
I have this same issue.

**Comment by Tizull** [comment]
I find that the plugin doesn't show up as an option in the GUI with the sidecar method as well.

**Comment by werne2j** [comment]
@Tizull When using the sidecar option, the plugin is automatically detected and so you would not see it in the UI

**Comment by BMonsalvatge** [comment]
Yea I forgot to reply but managed to sort this out by specifying helm values in the application manifest or by choosing helm from the dropdown.  However the parameters in the values.yaml do not seem to show up when choosing that.  Also the pathing inside of the repo doesn't work as well since setting up the sidecar.

However everything else functionally works, it'd just be nice to have those 2 details available via the GUI again.

**Comment by BMonsalvatge** [comment]
To provide some screenshots.  I would expect this section to show the values as parameters like it does by default: 
![image](https://user-images.githubusercontent.com/1095871/186950673-1e5de7a7-6014-4a12-94e7-1020cf784885.png)

@werne2j Not sure if this is expected when using the vault plugin.

**Comment by werne2j** [comment]
> However everything else functionally works, it'd just be nice to have those 2 details available via the GUI again.

This would be something for the Argo CD team. AVP is just a simple command line tool so we are constrained by whatever Argo CD allows.

**Comment by werne2j** [comment]
> To provide some screenshots. I would expect this section to show the values as parameters like it does by default:

When using the plugin, you are no longer getting the first class citizen Helm support. So you wouldnt see anything in the Helm section.

**Comment by BMonsalvatge** [comment]
Thanks for the update.  To clarify, this is just an issue of using a CMP Plugin in general and would effect every other CMP plugin and isn't anything specific to the vault plugin?

**Comment by werne2j** [comment]
This is a result of using a Custom Plugin in general, correct.

**Comment by daro1337** [comment]
> I tried going through the two sidecar methods specified here: https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/docs/usage.md with no success...
> 
> Additionally I am unable to specify the usage of a different values file other than values.yaml
> 
> With the following app manifest my app is still pulling the default `values.yaml`
> 
> ```yaml
> project: projectname
> source:
>   repoURL: 'https://myrepo'
>   path: test
>   targetRevision: HEAD
>   plugin:
>     env:
>       - name: helm_args
>          value: -f qa.yaml
> destination:
>   server: 'https://kubernetes.default.svc'
>   namespace: test-qa
> syncPolicy:
>   syncOptions:
>     - CreateNamespace=true
> ```

@BMonsalvatge  how did yo umanaged to use different values.yaml? I have simmilar ArgoApp manifest and my `stage.yaml` if ignored :(

**Comment by daro1337** [comment]
@BMonsalvatge Yeah :)
In the meantime, I read the argocd and [plugin documentation](https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/).

> Before reaching the init.command, generate.command, and discover.command commands, Argo CD prefixes all user-supplied environment variables (#3 above) with ARGOCD_ENV_. This prevents users from directly setting potentially-sensitive environment variables.

So [documentation for argocd-vault-plugin](https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-helm) i quite misleading..

What i tried to do was from docs `With additional Helm arguments > For argocd-cm ConfigMap configured plugins, add this to argod-cm ConfigMap:` :
```yaml
...
args: ["helm template $ARGOCD_APP_NAME ${helm_args} . --include-crds | argocd-vault-plugin generate -"]
...
```
and manifest for argocd they are sugesting:
```yaml
  source:
    path: your-app
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_args
          value: -f values-dev.yaml -f values-dev-tag.yaml

```

because of `ARGOCD_ENV_` prefix  it should be:

```yaml
args: ["helm template $ARGOCD_APP_NAME ${ARGOCD_ENV_helm_args} . --include-crds | argocd-vault-plugin generate -"]
```

I've fixed it and it's working fine with customized `vaules.yaml` files, As for security,well I agree..
