### ISSUE TITLE
Question regarding plugin helm and inline values file 

### ISSUE THREAD

**Issue by gruenerg** [argoproj-labs/argocd-vault-plugin#389]
Hi,

I have implemented in our environment the argocd-vault-plugin with helm and I have used the following documentation: https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-helm particular the topic "WITH AN INLINE VALUES FILE" for it. At the moment I am not able to get it to work and I have no further clues why it doesn't work.

Setup:
- Kubernetes - 1.20.14 
- ArgoCD - 2.4.8
- argocd-vault-plugin - 1.12.0
- Vault Dev - 1.10.3

This is a code snippet of my argocd-cm file:
```
- apiVersion: v1
  data:
    application.instanceLabelKey: argocd.argoproj.io/instance
    configManagementPlugins: |-
      - name: argocd-vault-plugin-helm
        generate:
          command: ["bash", "-c"]
          args: ['helm template "$ARGOCD_APP_NAME" -f <(echo "$HELM_VALUES") . | argocd-vault-plugin generate -']
      - name: argocd-vault-plugin
        generate:
          command: ["argocd-vault-plugin"]
          args: ["generate", "./"]
    exec.enabled: "false"
    server.rbac.log.enforce.enable: "false"
    url: ""
```

Then I have created a helm init package with `helm create mychart` and I am trying now to deploy it with just plain helm values at the first step.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-application
  namespace: argo-cd
spec:
  project: default
  syncPolicy:
    automated: {}
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://git.company.com/gruenerg/mychart.git
    targetRevision: v0.1.0
    path: "."
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: HELM_VALUES
          value: |
            replicaCount: 2
```

The application file was created in argocd, but the deployment just ignore my helm value to set replicaCount: 1 to replicaCount: 2.

I can not see any issues in the argocd logs:
Logs:
```
repo-server time="2022-08-17T14:43:54Z" level=info msg="manifest cache hit: &ApplicationSource{RepoURL:https://git.company.com/gruenerg/mychart.git,Path:.,TargetRevision:v0.1.0,Helm:nil,Kustomize:nil,Directory:nil,Plugin:&ApplicationSourcePlugin{Name:argocd-vault-plugin-helm,Env:[]*EnvEntry{&EnvEntry{Name:VAULT_SKIP_VERIFY,Value:true,},&EnvEntry{Name:HELM_VALUES,Value:replicaCount: 2\n,},},},Chart:,}/fb4925c33bcb589e570789cadf845e9777a6f7f5"                                                                                                                                                                                          

repo-server time="2022-08-17T14:43:54Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2022-08-17T14:43:54Z" grpc.time_ms=1.053 span.kind=server system=grpc
```
Anyone have any ideas why this isn't working?

Many thanks in advance.
