### ISSUE TITLE
ArgoCD Vault Plugin not Honoring Multitenancy

### ISSUE THREAD

**Issue by georgblumenschein** [argoproj-labs/argocd-vault-plugin#392]
**Describe the bug**
We have configured the ArgoCD Vault plugin with the Kubernetes secret configuration for multi-tenancy as described in the [documentation](https://argocd-vault-plugin.readthedocs.io/en/stable/config/#multitenancy) ("Using Kubernetes secrets for supplying AVP configuration"). Below, we added the important parts of our configuration.
​
```yaml
# argocd-cm.yaml
data:
  configManagementPlugins: |-
    - name: argocd-vault-plugin
      generate:
        command: ["sh", "-c"]
        args: ["argocd-vault-plugin generate -s ${ARGOCD_ENV_AVP_SECRET} ./"]
    - name: argocd-vault-plugin-helm
      init:
        command: [sh, -c]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME ${ARGOCD_ENV_helm_args} . | argocd-vault-plugin generate -s ${ARGOCD_ENV_AVP_SECRET} -"]
```
```yaml
# app1.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  project: system
  source:
    ...
    plugin:
      name: argocd-vault-plugin
      env:
        - name: AVP_SECRET
          value: argocd-vault-plugin-credentials
...
```
```
# vault-credentials.yaml - The secret for the playground app that should use another Vault AppRole
apiVersion: v1
stringData:
  AVP_AUTH_TYPE: "approle"
  AVP_TYPE: "vault"
  VAULT_ADDR: "https://our-vault-instance.com/"
  AVP_ROLE_ID: <ROLE_ID>
  AVP_SECRET_ID: <SECRET_ID>
kind: Secret
metadata:
  name: playground-vault-credentials
  annotations:
    avp.kubernetes.io/path: "path/to/secret"
type: Opaque
```
```yaml
# project.yaml - The project that contains the playground app
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: playground
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: playground applications
​
  sourceRepos:
    - <repoUrl>
​
  destinations:
    - namespace: "playground-*"
      name: <cluster>
​
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: storage.k8s.io
      kind: StorageClass
​
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
​
  orphanedResources:
    warn: false
```
```yaml
# playground.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground
spec:
  project: playground
  source:
    repoURL: <repoUrl>
    targetRevision: HEAD
    path: .
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_args
          value: -f <valuesFile>
        - name: AVP_SECRET
          value: playground-vault-credentials
  destination:
    name: <cluster>
    namespace: playground
```
Unfortunately, the ArgoCD Vault plugin still seems to use the `argocd-vault-plugin-credentials` instead of the `playground-vault-credentials` for the `playground` Application. We assume that, because we cannot read secrets from the `playground` Vault engine (which the approle of the playground app has access to), but only engines where the first approle has access to.
​
We also tried to hard code the credential name instead of passing them via environment variables but there the problem occured as well.
​
**To Reproduce**
Create the applications from above and try to create a secret that is in an engine where only the playground approle has access to.
​
**Expected behavior**
* We should not be able to read secrets from any engines the playground approle doesn't have access to
* We should be able to read all secrets the playground approle has access to
​
**Additional context**
* ArgoCD version: v2.4.2+c6d0c8b
* Vault Plugin Version: 1.12 (but the problem also occurred with version 1.11)
