### ISSUE TITLE
`sh -c helm dependency build ` failed exit status 1: Error: no cached repository

### ISSUE THREAD

**Issue by rm-rf-home** [argoproj-labs/argocd-vault-plugin#393]
**Describe the bug**
An Argo CD application is configured to use the vault plugin with an umbrella Helm Chart hosted in git:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
(...)
  source:
    plugin:
      name: argocd-vault-plugin-helm
    path: the/path
    repoURL: 'ssh://git@git-example.com:7999/repos/repo.git'
    targetRevision: thebranch
(...)
```
The umbrella Chart has another Helm Chart as dependency.
```
apiVersion: v2
(...)
dependencies:
  - name: another-chart
    version: 0.1.5
    repository: https://helm-example.com/charts/name/helm-poc
```
The plugin is configured like this:
```
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
    - name: argocd-vault-plugin-helm
      init:
        command: [sh, -c]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME . | argocd-vault-plugin generate -"]
```
Both the git repo and the Helm repo are successfully added in Argo CD as repositories.
The "helm dependency build" command fails with the following error message:
```
rpc error: code = Unknown desc = Manifest generation error (cached): `sh -c helm dependency build ` failed exit status 1: Error: no cached repository for helm-manager-9894e008a23e82901a4adbd36642eca2d4d8848dbfd3afba46e82d8c440a41de found. (try 'helm repo update'): open /.cache/helm/repository/helm-manager-9894e008a23e82901a4adbd36642eca2d4d8848dbfd3afba46e82d8c440a41de-index.yaml: no such file or directory
```

**Expected behavior**
Dependencies should be downloaded

**Additional context**
Red Hat OpenShift GitOps 1.5.5
argocd-vault-plugin v1.12.0
OpenShift version 4.8.44
Kubernetes version v1.21.11+6b3cbdd
Argo CD
{
    "Version": "v2.3.7+unknown",
    "BuildDate": "2022-08-01T21:40:18Z",
    "GitTreeState": "clean",
    "GoVersion": "go1.17.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "unable to determine ksonnet version: exec: \"ks\": executable file not found in $PATH",
    "KustomizeVersion": "v4.4.1 1970-01-01T00:00:00Z",
    "HelmVersion": "v3.8.0+g7ddadb4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
