### ISSUE TITLE
Resolving GET Error: EOF 

### ISSUE THREAD

**Issue by aMiss-aWry** [argoproj-labs/argocd-vault-plugin#403]
When attempting to retrieve a secret using argocd-vault-plugin, I get Error: Get "http://(vault link)/v1/configs/data/test": EOF. Is there a way to get a more detailed error message? 

`cat test.yaml | argocd-vault-plugin -c test-config.yaml generate -`
`Error: Get "http://(vault link)/v1/configs/data/test": EOF`

When using the same link in a curl request (i.e. curl -X 'GET' 'http://(vault link)/v1/configs/data/test' ...) it works perfectly fine. 

My vault configuration looks like:

test-config.yaml:
```
apiVersion: v1
data:
  AVP_TYPE: vault
  VAULT_ADDR: http://(vault link)
  AVP_AUTH_TYPE: token
  VAULT_TOKEN: "token here"
  VAULT_NAMESPACE: conf/example
  AUTH_TYPE: token
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
```

And the example secret I'm trying to generate looks like:

test.yaml:
```
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "configs/data/test"
type: Opaque
stringData:
  password: <user>
```

When I run 
```
curl -X 'GET' \
  'https://(vault link)/v1/configs/data/test' \
  -H 'accept: */*' \
  -H 'X-Vault-Token: (vault token)' \
  -H 'X-Vault-Namespace: conf/example'
```

It successfully returns the 'user' secret as expected. 

What might I be missing here? Any help is appreciated!

Edited to add in case of relevance: argocd-vault-plugin version:
argocd-vault-plugin 1.12.0 (9c7288a5b2d395fea19c1100f2cd07b547cc1ee2) BuildDate: 2022-07-07T15:13:35Z
