### ISSUE TITLE
Plugin not showing up in UI with CMP & init container method

### ISSUE THREAD

**Issue by michemoche** [argoproj-labs/argocd-vault-plugin#404]
**Describe the bug**
When trying to setup the plugin through the init container and CMP edition method, the plugin is not selectable in the UI, thus, it won't act on files

**To Reproduce**
I'm confused because I followed the official doc and[ this one](https://itnext.io/argocd-secret-management-with-argocd-vault-plugin-539f104aff05), but the outcome is the same, it's either my fat finger or a version issue

**Expected behavior**
The plugin section should be present in the UI 

**Additional context**
here are my two blocks 

init containers

```
  initContainers:
  - args:
    - wget -O /custom-tools/argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64
      && chmod +x /custom-tools/argocd-vault-plugin && ls -l /custom-tools/
    command:
    - sh
    - -c
    env:
    - name: AVP_VERSION
      value: 1.12.0
    image: alpine:3.8
    imagePullPolicy: IfNotPresent
    name: download-tools
    volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools

```

it's there in the argo pod 

```
k exec -ti argocd-repo-server-54dc77dcf5-j7wdm -c argocd-repo-server -- argocd-vault-plugin version
argocd-vault-plugin v1.12.0 (9c7288a5b2d395fea19c1100f2cd07b547cc1ee2) BuildDate: 2022-07-08T13:27:45Z
```

and the config (which works as we have oidc auth )

```
$ k get cm argocd-cm -o yaml
apiVersion: v1
data:
  configManagementPlugins: |-
    - name: argocd-vault-plugin-kustomize
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-plugin generate -"]
  oidc.config: |

```

argo version is v2.2.3, that is why I didn't use the side car solution (I tried it first though)

honestly I'm clueless right now, so fresh  and expert eyes on it will help me a lot :)
