### ISSUE TITLE
Can't template YAML using side-car

### ISSUE THREAD

**Issue by AmiditeX** [argoproj-labs/argocd-vault-plugin#407]
**Describe the bug**
YAML doesn't seem to be templated by the AVP when using sidecar containers.  
The YAML does get templated when manually placed INSIDE the AVP YAML pod, so the Vault configuration seems OK.

**To Reproduce**
- Deploy the AVP using Kustomize with these configurations:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-plugins
data:
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true
      # Note: this command is run _before_ anything is done, therefore the logic is to check
      # if this looks like a Kustomize bundle
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate -"
      lockRepo: false
  avp-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      # Note: this command is run _before_ any Helm templating is done, therefore the logic is to check
      # if this looks like a Helm chart
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
      generate:
        command:
          - sh
          - "-c"
          - |
            helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . |
            argocd-vault-plugin generate -
      lockRepo: false
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "."
      lockRepo: false
```
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      # Mount SA token for Kubernets auth
      # Note: In 2.4.0 onward, there is a dedicated SA for repo-server (not default)
      # Note: This is not fully supported for Kubernetes < v1.19
      automountServiceAccountToken: true

      # Each of the embedded YAMLs inside cmp-plugin ConfigMap will be mounted into it's respective plugin sidecar
      volumes:
        - configMap:
            name: argocd-plugins
          name: cmp-plugin
        - name: custom-tools
          emptyDir: {}

      # Download tools
      initContainers:
      - name: download-tools
        image: registry.access.redhat.com/ubi8
        env:
          - name: AVP_VERSION
            value: 1.11.0
        command: [sh, -c]
        args:
          - >-
            curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools

      containers:
      - name: argocd-repo-server
        envFrom:
        - secretRef:
          name: argocd-vault-plugin-credentials

      # argocd-vault-plugin with Helm
      - name: avp-helm
        command: [/var/run/argocd/argocd-cmp-server]
        image: quay.io/argoproj/argocd:v2.4.0
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp

          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-helm.yaml
            name: cmp-plugin

          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin

      # argocd-vault-plugin with Kustomize
      - name: avp-kustomize
        command: [/var/run/argocd/argocd-cmp-server]
        image: quay.io/argoproj/argocd:v2.4.0
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp

          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-kustomize.yaml
            name: cmp-plugin

          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin

      # argocd-vault-plugin with plain YAML
      - name: avp
        command: [/var/run/argocd/argocd-cmp-server]
        image: quay.io/argoproj/argocd:v2.4.0
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp

          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp.yaml
            name: cmp-plugin

          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin
```

- Commit a file using templated values from Vault:
```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: aaa
  labels:
    mylabel: "<path:store/data/path#test>"
    b: "a"
```

- See that the file gets synced by ArgoCD but goes into error because the label is invalid due to it not being templated : 
Sync failed: Namespace "aaa" is invalid: metadata.labels: Invalid value: "<path:store/data/path#test>": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

- Place the same file inside the avp pod that is supposed to parse YAML and template it 
- Run the argocd-vault-plugin generate command manually
- Witness that the file got correctly templated
![image](https://user-images.githubusercontent.com/11838502/191932855-02ae4c78-d825-4e30-af15-3f2364cb1461.png)

**Expected behavior**
The YAML inline-key should be replaced on the fly by the AVP.

**Comment by Veluu** [comment]
I have somehow a similar issue.

Installed ArgoCD with Terraform and I have Apllications generated by Applications.

Also, I use AWS Secrets Manager as the secrets backend.

The following creates "argocd-apps" application in ArgoCD.

```YAML
# Will try to move to ApplicatioSet instead
resource "helm_release" "argocd_apps" {
  depends_on = [
    helm_release.argocd
  ]
  name       = "argocd-apps"
  version    = "0.0.1"
  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argocd-apps"
  namespace  = "argocd"

  values = [
    <<YAML
    applications:
    - name: argocd-apps
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: argocd-apps
        repoURL: "git@myvcs/argocd-management.git"
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
YAML
  ]
}
```
The above application reads git@myvcs/argocd-management.git where I have a couple of actual appliactions defined. For example:

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    avp.kubernetes.io/path: "k8s-argocd-project-labels"
  labels:
    mylabel: myvalue
    myawslabel: <path:k8s-argocd-project-labels#label-1>
spec:
  project: default
  source:
    repoURL: "git@myvcs/argocd-applications.git"
    targetRevision: HEAD
    path: tenants-shared
  destination:
    server: https://kubernetes.default.svc
    namespace: example
```

If I consume the above file locally it works fine
```shell
$ argocd-vault-plugin generate - < example-application.yaml 
```
```YAML
kind: Application
metadata:
  annotations:
    avp.kubernetes.io/path: k8s-argocd-project-labels
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    myawslabel: mysecretlabelvalue
    mylabel: myvalue
  name: example
  namespace: argocd
spec:
  destination:
    namespace: example
    server: https://kubernetes.default.svc
  project: default
  source:
    path: tenants-shared
    repoURL: git@myvcs/argocd-applications.git
    targetRevision: HEAD
---
```

However, when ArgoCD applies it then there's an error as basically no replacement happens. I do not see any action in avp container logs.

Interestingly, everything works fine if I use the plugin on a "lower" level. Meaning, if I template deployments/services/secrets etc in repository/catalogue read by ArgoCD `Application` (instead of trying to template `Application` itself) kind then everything is fine.
