### ISSUE TITLE
Double quotes removed during replacement, causing problem with environment variables replacement

### ISSUE THREAD

**Issue by headyj** [argoproj-labs/argocd-vault-plugin#434]
**Describe the bug**
executing `argocd-vault-plugin generate`  remove double quotes or replace them by single one, causing issue with commands and variable replacement

**To Reproduce**
create a simple CronJob:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl
spec:
  schedule: "0 23 * * 1,3"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:latest
            env:
            - name: VAR1
              value: "vat1"
            - name: VAR2
              value: "var2"
            envFrom:
            - secretRef:
                name: curl
            imagePullPolicy: IfNotPresent
            args:
              - "-X"
              - "GET"
              - "https://my-test-url/$VAR1/$VAR2"
          restartPolicy: OnFailure
```
execute plugin: `cat cronjob.yml | argocd-vault-plugin generate -s vault-configuration -`
double quotes arround url are removed, causing the request to be invalid: `curl: (3) URL using bad/illegal format or missing URL`
moreover, if you try to add headers to your request, double quotes are replaced by single ones, so variable are not replaced:
```
[...]
args:
  - "-X"
  - "GET"
  - "https://my-test-url/$VAR1/$VAR2"
  - "PRIVATE-TOKEN: $TOKEN"
```
execute  `cat cronjob.yml | argocd-vault-plugin generate -s vault-configuration -`
```
[...]
args:
  - -X
  - GET
  - https://my-test-url/$VAR1/$VAR2
  - 'PRIVATE-TOKEN: $TOKEN'
```
**Expected behavior**
double quotes should be present after plugin execution

**Additional context**
```
$ argocd-vault-plugin version
argocd-vault-plugin v1.13.0 (6866b7206719e9b5b2ea4d7cb870e18f76534637) BuildDate: 2022-09-19T15:06:23Z
```
