### ISSUE TITLE
Can't see plugin in ArgoCD after sidecar installation

### ISSUE THREAD

**Issue by Amet13** [argoproj-labs/argocd-vault-plugin#436]
**Describe the bug**
After installation plugin with sidecar method I can't use it in ArgoCD.

**To Reproduce**

ArgoCD installed from helm chart:
```
repoServer:
  volumes:
    - name: custom-tools
      emptyDir: {}
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
  initContainers:
    - name: download-tools
      image: registry.access.redhat.com/ubi8
      env:
        - name: AVP_VERSION
          value: 1.13.0
      command: [sh, -c]
      args:
        - >-
          curl -s -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
          chmod +x argocd-vault-plugin &&
          mkdir -p /custom-tools/ &&
          mv argocd-vault-plugin /custom-tools/ &&
          ls -lha /custom-tools/ && echo OK
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  extraContainers:
  - name: avp
    command: [/var/run/argocd/argocd-cmp-server]
    image: registry.access.redhat.com/ubi8
    env:
    - name: AVP_TYPE
      value: awssecretsmanager
    - name: AWS_REGION
      value: us-east-2
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
    volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins
      # Register plugins into sidecar
      - mountPath: /home/argocd/cmp-server/config/plugin.yaml
        subPath: avp.yaml
        name: cmp-plugin
      # Important: Mount tools into $PATH
      - name: custom-tools
        subPath: argocd-vault-plugin
        mountPath: /usr/local/bin/argocd-vault-plugin

extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cmp-plugin
    data:
      avp.yaml: |
        apiVersion: argoproj.io/v1alpha1
        kind: ConfigManagementPlugin
        metadata:
          name: argocd-vault-plugin
        spec:
          allowConcurrency: true
          discover:
            find:
              command:
                - find
                - "."
                - -name
                - Chart.yaml
          generate:
            command:
              - sh
              - "-c"
              - |
                helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_helm_args} . | argocd-vault-plugin generate -
          lockRepo: false
        ---
```

**Expected behavior**
I expect to see the plugin working correctly

**Screenshots/Verbose output**
<img width="1087" alt="Screenshot 2022-11-28 at 17 44 58" src="https://user-images.githubusercontent.com/5184847/204396773-f3d9bee1-eff7-4a9f-9ebc-b89dafcb22e9.png">
