### ISSUE TITLE
Manifest generation error (cached): plugin sidecar failed

### ISSUE THREAD

**Issue by pdruzhinin** [argoproj-labs/argocd-vault-plugin#437]
I'm trying to use the plugin installed in sidecar mode to pull the secrets from Azure Key Vault, and I think I'm missing something somewhere, but I'm not sure what.
When trying to sync, the error I'm getting in the repo-server log is:

`time="2022-11-29T18:20:31Z" level=error msg="finished unary call with code Unknown" error="Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: error sending file to cmp-server: error sending tgz file to cmp-server: client stream context error: context canceled" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2022-11-29T18:20:31Z" grpc.time_ms=194.448 span.kind=server system=grpc`

There's absolutely nothing in the sidecar logs:

```
time="2022-11-29T18:14:18Z" level=info msg="ArgoCD ConfigManagementPlugin Server is starting" built="2022-11-28T16:51:33Z" commit=0c7de210ae66bf631cc4f27ee1b5cdc0d04c1c96 version=v2.5.3+0c7de21
time="2022-11-29T18:14:18Z" level=info msg="argocd-cmp-server v2.5.3+0c7de21 serving on /home/argocd/cmp-server/plugins/argocd-vault-plugin-kustomize.sock"
```

The secret it's trying to process looks like this:
```
apiVersion: v1
data:
  consumer-monitoring.properties: confluent-replicator-to-utopus-consumer-monitoring-properties
  consumer.properties: confluent-replicator-to-utopus-consumer-properties
  producer-monitoring.properties: confluent-replicator-to-utopus-producer-monitoring-properties
  producer.properties: confluent-replicator-to-utopus-producer-properties
  replication.properties: confluent-replicator-to-utopus-replication-properties
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "***-***-keyvault"
  name: confluent-replicator
type: Opaque
```

And the plugin configmap is as follows:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true

      # Note: this command is run _before_ anything is done, therefore the logic is to check
      # if this looks like a Kustomize bundle
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
      generate:
        command:
          - sh
          - "-c"
          - "argocd-vault-plugin generate $(kustomize build .) -s ***-argocd:vault-configuration"
      lockRepo: false
---
```

For configuration, I have the following secret defined:

```
apiVersion: v1
data:
  AVP_TYPE: YXp1cmVrZXl2YXVsdA==
  AZURE_TENANT_ID: ***
  AZURE_CLIENT_ID: ***
  AZURE_CLIENT_SECRET: ***
kind: Secret
metadata:
  name: vault-configuration
  namespace: ***-argocd
type: Opaque
```

And the values for ArgoCD Helm chart are like this (excerpt, repoServer section only):

```
repoServer:
  volumes:
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
    - name: custom-tools
      emptyDir: {}
  initContainers:
  - name: download-tools
    image: registry.access.redhat.com/ubi8
    env:
      - name: AVP_VERSION
        value: 1.13.1
    command: [sh, -c]
    args:
      - >-
        curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
        chmod +x argocd-vault-plugin &&
        mv argocd-vault-plugin /custom-tools/
    volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
  volumeMounts:
  - name: custom-tools
    mountPath: /usr/local/bin/argocd-vault-plugin
    subPath: argocd-vault-plugin
  serviceAccount:
    automountServiceAccountToken: true
  extraContainers:
  # argocd-vault-plugin with Kustomize
  - name: avp-kustomize
    command: [/var/run/argocd/argocd-cmp-server]
    image: quay.io/argoproj/argocd:v2.4.0
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
    volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins
      - mountPath: /tmp
        name: tmp

      # Register plugins into sidecar
      - mountPath: /home/argocd/cmp-server/config/plugin.yaml
        subPath: avp-kustomize.yaml
        name: cmp-plugin

      # Important: Mount tools into $PATH
      - name: custom-tools
        subPath: argocd-vault-plugin
        mountPath: /usr/local/bin/argocd-vault-plugin
```

Any help pointing me to what it is I'm doing wrong is highly appreciated :)
