### ISSUE TITLE
Error log not printed in container logs

### ISSUE THREAD

**Issue by meyfa** [argoproj-labs/argocd-vault-plugin#449]
**Describe the bug**
When errors occur in the vault plugin sidecar container (specifically, the generate command), they aren't logged to the container logs.

**To Reproduce**
1. Cause some kind of problem with the to-be-deployed Application, such as:
    * Invalid Helm chart
    * Missing Helm dependencies
2. See no output in the container logs (after the command itself), and neither inside the ArgoCD UI

For reference, the command we're executing is:

```
helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE --include-crds . | argocd-vault
-plugin generate -
```

We also got an init command that does `helm dependency update` to deal with dependencies.

**Expected behavior**
Expected the error to show up in the logs. When executing the same command in a container shell (of the AVP container), we're getting:

```sh
/tmp/renovate $ export ARGOCD_APP_NAME=renovate ARGOCD_APP_NAMESPACE=renovate
/tmp/renovate $ helm dependency update
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://docs.renovatebot.com/helm-charts" chart repository
Saving 1 charts
Downloading renovate from repo https://docs.renovatebot.com/helm-charts
Deleting outdated charts
/tmp/renovate $ helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE --include-crds . | argocd-vault
-plugin generate -
Error: execution error at (renovate/charts/renovate/templates/cronjob.yaml:8:6):

 ERROR: You must have at least batch/v1beta1 to use CronJob

Use --debug flag to render out invalid YAML
/tmp/renovate $
```

But in the log of the actual CMP container we're seeing none of that:

```
time="2023-01-03T22:06:05Z" level=info msg="sh -c helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE --include-crds . | argocd-vault-plugin generate -" dir=/tmp/_cmp_server/089ed89b-c708-49e9-b382-8caf1dbc6163/services/renovate execID=a205a
time="2023-01-03T22:06:05Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-01-03T22:06:03Z" grpc.time_ms=2126.328 span.kind=server system=grpc
```

**Comment by ptimofee** [comment]
just change 
```
      generate:
        command:
          - sh
          - "-c"
          - |
            helm template $ARGOCD_APP_NAME --include-crds . |
            argocd-vault-plugin generate -
      lockRepo: false
```
to
```
      generate:
        command:
          - bash
          - "-o"
          - "pipefail"
          - "-c"
          - |
            helm template $ARGOCD_APP_NAME --include-crds . |
            argocd-vault-plugin generate -
      lockRepo: false
```
