### ISSUE TITLE
Cannot use AWSPREVIOUS version stage

### ISSUE THREAD

**Issue by carlosrmendes** [argoproj-labs/argocd-vault-plugin#453]
I tried to follow the example present on this doc: https://argocd-vault-plugin.readthedocs.io/en/stable/backends/#versioned-secrets_1, trying to generate with the previous value of the aws secret:
```
echo "apiVersion: v1
kind: Secret
metadata:
  name: test
type: Opaque
stringData:
  password: <path:/my/test/secret#password#AWSPREVIOUS>" | argocd-vault-plugin generate -
```

But I got the following error:
```
Error: Replace: could not replace all placeholders in Template:
InvalidParameter: 1 validation error(s) found.
- minimum field size of 32, GetSecretValueInput.VersionId.
```
