### ISSUE TITLE
Sync Error with Vault TLS enabled

### ISSUE THREAD

**Issue by rfashwall** [argoproj-labs/argocd-vault-plugin#456]
**Describe the bug**
We have Self Managed Vault instance where we enabled TLS using self managed certification.

Using K8s access method, when we enabled TLS, we had the below issue 

```
x509: certificate signed by unknown authority 
```

After more investigation, there are some extra variables that could be set in `vault-configuration` secret found in the link:
https://developer.hashicorp.com/vault/docs/commands#vault_cacert

- vault-configuration
```
apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
stringData:
    VAULT_ADDR: https://vault.hashicorp.svc.cluster.local:8200
    AVP_TYPE: vault
    AVP_AUTH_TYPE: k8s
    AVP_K8S_ROLE: dna-ops-argocd
    VAULT_CACERT: /vault/tls/vault.ca
    VAULT_CAPATH:  /vault/tls/vault.ca
    VAULT_CLIENT_CERT: /vault/tls/vault.crt
    VAULT_CLIENT_KEY: /vault/tls/vault.key
```

However, the solution needs the key and ca certs to be mounted in `argocd-repo-server` which could be a security issue
Not including these fires the below error
```
error encountered setting up default configuration: both client cert and client key must be provided
```

**Expected behavior**
Adding the cert should be enough to validated that the request is secured

Should the behaviour change or is the key always needed?
