### ISSUE TITLE
Does not work with argocd multiple sources 

### ISSUE THREAD

**Issue by ilya251188** [argoproj-labs/argocd-vault-plugin#458]
argo-vault-plugin version 1.13.1 installed as sidecar container
Tried add this manifest
```
project: myProject
source:
  repoURL: 'https://gitlab.local/k8s/testproject/testapp.git'
  path: ./
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: test
sources:
  - repoURL: 'https://gitlab.local/k8s/testproject/testapp.git'
    path: ./
    targetRevision: master
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f $app_values/global/values.yaml
  - repoURL: 'https://git.local/k8s/testproject/env.git'
    targetRevision: feature/argocd
    ref: app_values
```

And I get an error:
``
Unable to save changes: application spec for testapp is invalid: InvalidSpecError: Unable to generate manifests in ./: rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `sh -c helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . | argocd-vault-plugin generate - ` failed exit status 126: sh: 2: argocd-vault-plugin: Exec format error Error: open /global/values.yaml: no such file or directory
``

Maybe I'm doing something wrong)

**Comment by mircyb** [comment]
i have same issue, anyone have solution?

**Comment by Hax7** [comment]
remove plugin part and try again as it's not required with sidecar method anymore

**Comment by ilya251188** [comment]
> remove plugin part and try again as it's not required with sidecar method anymore

If I understand correctly, the same error
```
 sources:
    - path: ./
      repoURL: 'https://gitlab.local/k8s/testproject/testapp.git'
      targetRevision: master
      plugin:
        env:
          - name: HELM_ARGS
            value: '-f $app_values/global/values.yaml'
    - repoURL: 'https://git.local/k8s/testproject/env.git'
      targetRevision: feature/argocd
      ref: app_values
```

```Unable to create application: application spec for testapp is invalid: InvalidSpecError: Unable to generate manifests in ./: rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `sh -c helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . | argocd-vault-plugin generate - ` failed exit status 126: sh: 2: argocd-vault-plugin: Exec format error Error: open /global/values.yaml: no such file or directory```

**Comment by jete-vian** [comment]
Seems the issue is with ArgoCD.
https://github.com/argoproj/argo-cd/issues/12476

**Comment by werne2j** [comment]
@ilya251188 was the Argo CD issue linked above able to help your issue?

**Comment by alekseydemidov** [comment]
Does somebody have any updates? Can we hope multiple sources will be supported? 
Currently, we have to use single source with helm dependency like as workaround.

**Comment by olzemal** [comment]
Our current workaround is to pull and store the helm chart into the same git repo we store the values in.
```
repo
|- chart-1.0
  |- Chart.yaml
  |- ...
  |- our-values.yaml
```
So the app would look something like that
```
...
source:
  repoURL: 'https://our-git/our-repo.git'
  path: chart-1.0
  targetRevision: HEAD
  plugin:
    name: argocd-vault-plugin-helm
    env:
      - name: HELM_ARGS
        value: '-f our-values.yaml'
```

**Comment by brysk** [comment]
Are there any plans to fix this in future? I'm facing the same issue and it's quite disturbing

**Comment by Diliz** [comment]
Same here, currently can't use the multiple sources with a custom plugin :/

**Comment by subigre** [comment]
Except the workaround proposed by @olzemal, did someone find another alternative?

I am having the same issue and trying to find a solution for use case when Helm charts are published by an external third party such as Bitnami and I just maintain the `values.<environment>.yaml` in my own GitHub repo.

**Comment by welcomeboredom** [comment]
The dirty solution might be to clone the git repository with values files explicitly during `init` phase of plugin. I'm attaching pseudocode example of what I have in mind. It's not tested and most likely not working out of the box:
```
      argocd-vault-plugin-helm:
        init:
          command: [sh, -c]
          args: ["git clone https://github.com/my-values-repo ../my-values-repo"]
        generate:
          command: ["bash", "-o", "pipefail", "-c"]
          args: ['helm template $ARGOCD_APP_NAME --include-crds -n $ARGOCD_APP_NAMESPACE -f ../my-values-repo/values.yaml} . | argocd-vault-plugin generate -']
```

Git binary must be of course available inside the sidecar (if you use default argocd image it's there). The problem might be credentials so you might have to mount there SSH key from some secret or use some username/password combination. `my-values-repo` string can be probably replaced with `$ARGOCD_APP_VALUES_REPO` env varible defined in Application manifest.
