### ISSUE TITLE
missing client token when using sidecar and k8s auth type

### ISSUE THREAD

**Issue by omriarieli** [argoproj-labs/argocd-vault-plugin#462]
**Describe the bug**
Im trying to use this as a side car and get error 400 missing client token

**To Reproduce**
1. configure argocd side car as per InitContainer and configuration via sidecar [instructions](https://argocd-vault-plugin.readthedocs.io/en/stable/installation/)
2. Create a secret for vault configuration
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
type: Opaque
stringData:
  AVP_AUTH_TYPE: "k8s"
  AVP_K8S_MOUNT_PATH: "my-mount-path"
  AVP_K8S_ROLE: "argocd"
  AVP_TYPE: "vault"
  VAULT_ADDR: "https://my-valt-adrress.com"
```
3. apply a sample application with plugin env
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-test-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    env: test
spec:
  destination:
    namespace: test
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://chart-repo.com'
    targetRevision: 0.3.21
    chart: my-chart
    plugin:
      env:
        - name: ARGOCD_ENV_HELM_VALUES
          value: |
            redis:
              auth:
                password: <path:mycompany/dev/data/pws-helm#REDIS_PASS>
```

**Expected behavior**
The REDIS_PASS env var gets the value from vault

**Screenshots/Verbose output**
Fllowing the argocd-vault-plugin sidecar logs i see an error:
`time="2023-02-12T22:52:02Z" level=error msg="finished streaming call with code Unknown" error="error generating manifests: `bash -c helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo \"$ARGOCD_ENV_HELM_VALUES\") . |\nargocd-vault-plugin generate -s argocd-vault-plugin-credentials --verbose-sensitive-output -\n` failed exit status 1: 2023/02/12 22:52:02 reading configuration from secret argocd-vault-plugin-credentials\n2023/02/12 22:52:02 parsed secret name as argocd-vault-plugin-credentials from namespace argocd\n2023/02/12 22:52:02 Setting VAULT_ADDR to https://my-valt-adrress.com for backend SDK\n2023/02/12 22:52:02 reading configuration from environment, overriding any previous settings\n2023/02/12 22:52:02 AVP configured with the following settings:\n\n2023/02/12 22:52:02 avp_kv_version: 2\n\n2023/02/12 22:52:02 argocd_env_helm_values: redis:\n  auth:\n    password: <path:mycompany/dev/data/pws-helm#REDIS_PASS>\n\n\n2023/02/12 22:52:02 avp_auth_type: k8s\n\n2023/02/12 22:52:02 avp_k8s_mount_path: my-mount-path\n\n2023/02/12 22:52:02 avp_k8s_role: argocd\n\n2023/02/12 22:52:02 avp_type: vault\n\n2023/02/12 22:52:02 vault_addr: ttps://my-valt-adrress.com\n\n2023/02/12 22:52:02 Hashicorp Vault authenticating with Vault role argocd using Kubernetes service account token /var/run/secrets/kubernetes.io/serviceaccount/token read from XXXXX kubernetes service account token XXXXX\nError: Error making API request.\n\nURL: PUT https://my-valt-adrress.com/v1/my-mount-path/login\nCode: 400. Errors:\n\n* missing client token\nUsage:\n  argocd-vault-plugin generate <path> [flags]\n\nFlags:\n  -c, --config-path string         path to a file containing Vault configuration (YAML, JSON, envfile) to use\n  -h, --help                       help for generate\n  -s, --secret-name string         name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>\n      --verbose-sensitive-output   enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-02-12T22:51:59Z" grpc.time_ms=2683.142 span.kind=server system=grpc`

it looks like its trying to authenticate with a vault token even though i set `AVP_AUTH_TYPE: "k8s"`
