### ISSUE TITLE
Helm charts and plugin use

### ISSUE THREAD

**Issue by funes79** [argoproj-labs/argocd-vault-plugin#463]
Hi, I configured the plugin following the docs (patching the repo-server and adding custom-tools).

I do have however a problem to figure out how to use the plugin with existing helm apps like this:

It fails with `Manifest generation error (cached): multiple application sources defined: Helm,Plugin`.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.3.15
    helm:
      releaseName: redis
      parameters:
        - name: auth.enabled
          value: "true"
        - name: commonConfiguration
          value: "notify-keyspace-events KEA"
        - name: auth.password
          value: "<argocd-secret2>"
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_args
          value: -f values.yaml   
```

I do have another application in ArgoCD where the plugin works fine. This is not a helm app. 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:MYORG/myrepo.git'
    path: manifests_main/myapp
    targetRevision: main
    plugin:
      name: argocd-vault-plugin
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myapp
  syncPolicy:
    automated: {}
```

and it pulls the myrepo.git where I have a secret defined with a placehold pointing to SecretsManager.
```
kind: Secret
apiVersion: v1
metadata:
  name: test-secret3
  namespace: myapp  
  annotations:
    avp.kubernetes.io/path: eks/argocd
type: Opaque
stringData:
  password: <argocd-secret1>
```
