### ISSUE TITLE
ArgoCD Vault Plugin not addressable by name 

### ISSUE THREAD

**Issue by christianknell** [argoproj-labs/argocd-vault-plugin#481]
**Describe the bug**

I have defined the Argo Vault Plugin as a CMP via the new Sidecar-Approach according the [ArgoCD documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#sidecar-plugin) and the [Argo Vault Plugin for Helm documentation](https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#simple).

When adding the plugin name to my application spec I receive the following error:

```
rpc error: code = Unknown desc = config management plugin not supported. plugin name argocd-vault-plugin-helm
```

**To Reproduce**

The Application containing the reference to the CMP:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <SOME_APPLICATION_NAME>
spec:
  project: <SOME_PROJECT>
  source:
    repoURL: '<GIT_REPOSITORY>'
    path: <PATH_IN_GIT_REPOSITORY>
    targetRevision: <BRANCH_IN_GIT_REPOSITORY>
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: AVP_K8S_ROLE
          value: <VAULT_ROLE>
        - name: HELM_ARGS
          value: '-f values.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: <SOME_NAMESPACE>
```

The ConfigMap containing the definition of my CMP:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-config-management-plugin
data:
  avp-helm.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
      generate:
        command: [sh, -c]
        args: ["helm template $ARGOCD_APP_NAME --include-crds -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . | argocd-vault-plugin generate -"]
      init:
        command: [sh, -c]
        args: ["helm dependency update"]
      lockRepo: false
```

The Pod specification of the Repo Server using this CMP as Sidecar (only relevant sections are shown):

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: argocd-clb01-repo-server
spec:
  containers:
    - name: avp-helm
      image: registry.access.redhat.com/ubi8
      command: [/var/run/argocd/argocd-cmp-server]
      env:
        - name: VAULT_ADDR
          value: <VAULT_URL>
        - name: AVP_TYPE
          value: vault
        - name: AVP_AUTH_TYPE
          value: k8s
        - name: AVP_K8S_MOUNT_PATH
          value: <VAULT_MOUNT_PATH>
        - name: HELM_CACHE_HOME
          value: /tmp/helm/cache
        - name: HELM_CONFIG_HOME
          value: /tmp/helm/config
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: argocd-config-management-plugin
          subPath: avp-helm.yaml
        - mountPath: /usr/local/bin/argocd-vault-plugin
          name: custom-tools
          subPath: argocd-vault-plugin
        - mountPath: /usr/local/bin/helm
          name: custom-helm
          subPath: helm
  initContainers:
    - name: copyutil
      image: registry.redhat.io/openshift-gitops-1/argocd-rhel8@sha256:3a0f7d98d98ae8fb3ab53506577e9647130e55c900952ed751ce08ef727a682f
      command: ["cp", "-n", "/usr/local/bin/argocd", "/var/run/argocd/argocd-cmp-server"]
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
    - name: download-tools
      image: 'quay.io/linuxserver.io/baseimage-alpine:3.8'
      command: ["sh", "-c"]
      args: ["wget -O /custom-tools/argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v1.13.1/argocd-vault-plugin_1.13.1_linux_amd64 && chmod +x /custom-tools/argocd-vault-plugin"]
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
    - name: custom-helm
      image: 'quay.io/linuxserver.io/baseimage-alpine:3.8'
      command: ["sh", "-c"]
      args: ["wget -O /custom-helm/helm.tar.gz https://get.helm.sh/helm-v3.11.1-linux-amd64.tar.gz && cd /custom-helm &&  tar -xzvf ./helm.tar.gz && chmod +x /custom-helm/linux-amd64/helm && mv /custom-helm/linux-amd64/helm /custom-helm/helm"]
      volumeMounts:
        - mountPath: /custom-helm
          name: custom-helm
  volumes:
    - name: tmp
      emptyDir: {}
    - name: var-files
      emptyDir: {}
    - name: plugins
      emptyDir: {}
    - name: custom-tools
      emptyDir: {}
    - name: custom-helm
      emptyDir: {}
    - name: argocd-config-management-plugin
      configMap:
        name: argocd-config-management-plugin
```

If I remove the name of the CMP inside the Application spec everything works as expected.

**Expected behavior**

The newly installed CMP can be referenced with the name attribute inside the source section of the Application spec.

**Version**
- RedHat OpenShift GitOps Operator: v1.7.2
- ArgoCD Version: v2.5.11
- Argo Vault Plugin: v1.13.1
- Helm Version: v.3.11.1

```shell
$ argocd version
argocd: v2.5.11+unknown
  BuildDate: 2023-02-13T09:50:50Z
  GitCommit: 
  GitTreeState: clean
  GoVersion: go1.18.7
  Compiler: gc
  Platform: linux/amd64
```
