### ISSUE TITLE
Plugin to work with multi source argo deployment

### ISSUE THREAD

**Issue by yonahd** [argoproj-labs/argocd-vault-plugin#492]
**Is your feature request related to a problem? Please describe.**
ArgoCD now supports creating an application using multiple sources e.g.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $values/charts/prometheus/values.yaml
  - repoURL: 'https://git.example.gom/org/value-files.git'
    targetRevision: dev
    ref: values

```
Using multi-source together with the plugin doesn't seem to work.

**Describe the solution you'd like**
The way I'd like this to work is having the AVP work together with the multisource e.g.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: grafana
    targetRevision: 6.53.0
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_args
          value: '-f $values/dev-values.yaml'
  - repoURL: 'https://git.example.gom/org/value-files.git'
    targetRevision: HEAD
    ref: values
```

If this can work together in some other way That would be great too.
