### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by 13567436138** [argoproj-labs/argocd-vault-plugin#495]
**Describe the bug**

**To Reproduce**
secret/argocd-vault-plugin/cmp-plugin.yaml

kubectl apply -f cmp-plugin.yaml -n argocd

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate -"
      lockRepo: false
  avp-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
      generate:
        command:
          - sh
          - "-c"
          - |
            helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . |
            argocd-vault-plugin generate -
      lockRepo: false
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        fileName: "./argocd-vault-plugin"
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "."
      lockRepo: false
---
```

secret/argocd-vault-plugin/patch2.yaml

kubectl patch -n argocd  deploy argocd-repo-server --patch "$(cat patch2.yaml)"

```
spec:
  template:
    spec:
      automountServiceAccountToken: true
      volumes:
        - configMap:
            name: cmp-plugin
          name: cmp-plugin
        - name: custom-tools
          emptyDir: {}
      initContainers:
      - name: download-tools
        image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/argocd-vault-plugin:v1
        imagePullPolicy: IfNotPresent
        command: [sh, -c]
        args:
          - >-
            cp /argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-plugin
          subPath: argocd-vault-plugin
        envFrom:
          - secretRef:
              name: vault-configuration
      - name: avp-helm
        command: [/var/run/argocd/argocd-cmp-server]
        image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/argocd:v2.6.7
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-helm.yaml
            name: cmp-plugin
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin
      - name: avp-kustomize
        command: [/var/run/argocd/argocd-cmp-server]
        image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/argocd:v2.6.7
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-kustomize.yaml
            name: cmp-plugin
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin
      - name: avp
        command: [/var/run/argocd/argocd-cmp-server]
        image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/argocd:v2.6.7
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp.yaml
            name: cmp-plugin
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin
```

secret/argocd-vault-plugin/vault-configuration.yaml

kubectl apply -f vault-configuration.yaml -n argocd

```
apiVersion: v1
stringData:
  VAULT_ADDR: http://192.168.229.148:31758
  AVP_AUTH_TYPE: k8s
  AVP_MOUNT_PATH: auth/kubernetes
  AVP_K8S_ROLE: myapp
  AVP_TYPE: vault
  AVP_K8S_TOKEN_PATH: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
```

```
kubectl exec -ti vault-0 -n vault /bin/sh 

vault policy write app app-policy.hcl

[root@mycompany secret]# cat app-policy.hcl 
path "kv/*" {
  capabilities = ["read"]
}

vault auth enable kubernetes

vault write auth/kubernetes/config \
   token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
   kubernetes_host=https://${KUBERNETES_PORT_443_TCP_ADDR}:443 \
   kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt


vault write auth/kubernetes/role/myapp \
   bound_service_account_names=argocd-repo-server \
   bound_service_account_namespaces=argocd \
   policies=app \
   ttl=1024h
   
   
   
   
vault kv put kv/cred username=mark password=123

```

secret/argocd-vault-plugin/ap-clusterResourceWhitelist.yaml

kubectl apply -f ap-clusterResourceWhitelist.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: cluster1
    - server: https://192.168.229.156:6443
      namespace: demo
```

secret/app-argocd-vault-plugin-configmap.yaml

kubectl apply -f app-argocd-vault-plugin-configmap.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    namespace: demo
    name: cluster1
  source:
    repoURL: https://gitee.com/hxpgit/argocd.git
    path: demo1/secretManager/argocd-vault-plugin
    targetRevision: HEAD 
    plugin:
      env:
      - name: VAULT_ADDR
        value: http://vault-active.vault.svc:8200
      - name: AVP_AUTH_TYPE
        value: k8s
      - name: AVP_MOUNT_PATH
        value: auth/kubernetes
      - name: AVP_K8S_ROLE
        value: myapp
      - name: AVP_KV_VERSION
        value: "2"
      - name: AVP_TYPE
        value: vault
      - name: AVP_K8S_TOKEN_PATH
        value: /var/run/secrets/kubernetes.io/serviceaccount/token
  project: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

```

```

```
[root@mycompany secretManager]# argocd app sync app
TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE
2023-04-21T00:42:49-07:00             Secret        demo    example-annotation   Unknown                       

Name:               argocd/app
Project:            project
Server:             cluster1
Namespace:          demo
URL:                https://argocd-server.argocd.svc.cluster.local/applications/app
Repo:               https://gitee.com/hxpgit/argocd.git
Target:             HEAD
Path:               demo1/secretManager/argocd-vault-plugin
SyncWindow:         Sync Allowed
Sync Policy:        Automated (Prune)
Sync Status:        Unknown
Health Status:      Healthy

Operation:          Sync
Sync Revision:      
Phase:              Error
Start:              2023-04-21 00:42:49 -0700 PDT
Finished:           2023-04-21 00:42:49 -0700 PDT
Duration:           0s
Message:            ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `argocd-vault-plugin generate .` failed exit status 1: Error: Error making API request.

URL: PUT http://vault-active.vault.svc:8200/v1/auth/kubernetes/login
Code: 403. Errors:

* permission denied
Usage:
  argocd-vault-plugin generate <path> [flags]

Flags:
  -c, --config-path string         path to a file containing Vault configuration (YAML, JSON, envfile) to use
  -h, --help                       help for generate
  -s, --secret-name string         name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>
      --verbose-sensitive-output   enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr

GROUP  KIND    NAMESPACE  NAME                STATUS   HEALTH  HOOK  MESSAGE
       Secret  demo       example-annotation  Unknown                
FATA[0000] Operation has completed with phase: Error 
```

**Expected behavior**

**Screenshots/Verbose output**

If you've tried running `argocd-vault-plugin generate` with `--verbose-sensitive-output` to help debug, please include that output here after redacting any secrets.

**Additional context**
