### ISSUE TITLE
 Error: secrets "argocd-vault-plugin-credentials" not found

### ISSUE THREAD

**Issue by 13567436138** [argoproj-labs/argocd-vault-plugin#497]
**Describe the bug**

**To Reproduce**
secret/argocd-vault-plugin/vault-configuration-in-cmdline.yaml

kubectl apply -f vault-configuration-in-cmdline.yaml -n argocd

```
apiVersion: v1
stringData:
  ARGOCD_ENV_VAULT_ADDR: http://192.168.229.148:31758
  ARGOCD_ENV_AVP_AUTH_TYPE: k8s
  ARGOCD_ENV_AVP_MOUNT_PATH: auth/kubernetes
  ARGOCD_ENV_AVP_K8S_ROLE: myapp
  ARGOCD_ENV_AVP_TYPE: vault
  ARGOCD_ENV_AVP_K8S_TOKEN_PATH: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
```

secret/argocd-vault-plugin/cmp-plugin-with-cmdline.yaml

kubectl apply -f cmp-plugin-with-cmdline.yaml -n argocd

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate  -s argocd:argocd-vault-plugin-credentials -"
      lockRepo: false
  avp-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
      generate:
        command:
          - sh
          - "-c"
          - |
            helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . |
            argocd-vault-plugin generate  -s argocd:argocd-vault-plugin-credentials -
      lockRepo: false
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        fileName: "./argocd-vault-plugin"
      generate:
        command:
          - argocd-vault-plugin
          - generate
          -  -s argocd:argocd-vault-plugin-credentials
          - "."
      lockRepo: false
---
```

rbac.yaml

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-repo-server-secret-read
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-repo-server-secret-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-repo-server-secret-read
subjects:
- kind: ServiceAccount
  name: argocd-repo-server
  namespace: argocd
```

secret/argocd-vault-plugin/ap-clusterResourceWhitelist.yaml

kubectl apply -f ap-clusterResourceWhitelist.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: cluster1
    - server: https://192.168.229.156:6443
      namespace: demo
```

secret/app-argocd-vault-plugin-without-env.yaml

kubectl apply -f app-argocd-vault-plugin-without-env.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    namespace: demo
    name: cluster1
  source:
    repoURL: https://gitee.com/hxpgit/argocd.git
    path: demo1/secretManager/argocd-vault-plugin
    targetRevision: HEAD 
    plugin: {}
  project: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

Duration:           0s
Message:            ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `argocd-vault-plugin generate -s argocd:argocd-vault-plugin-credentials .` failed exit status 1: Error: secrets "argocd-vault-plugin-credentials" not found
Usage:

**Expected behavior**

**Screenshots/Verbose output**

If you've tried running `argocd-vault-plugin generate` with `--verbose-sensitive-output` to help debug, please include that output here after redacting any secrets.

**Additional context**

**Comment by werne2j** [comment]
I would make sure that the service account does actually have the role binding and that is being applied to your sidecar containers.

**Comment by 13567436138** [comment]
it has role binding ,or it will through out you have no permission to read secrets.

**Comment by 13567436138** [comment]
```
放到repo容器里执行没问题，sync有问题Error: secrets " argocd-vault-plugin-credentials" not found


rgocd@argocd-repo-server-6c48d8bd6-cv45q:~/cmp-server/plugins/repo$ argocd-vault-plugin generate  -s argocd-vault-plugin-credentials .   
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: kv/data/cred
  name: example-annotation
stringData:
  password: "123"
  username: mark
type: Opaque
---
argocd@argocd-repo-server-6c48d8bd6-cv45q:~/cmp-server/plugins/repo$ cat a.yaml 
kind: Secret
apiVersion: v1
metadata:
  name: example-annotation
  annotations:
    avp.kubernetes.io/path: "kv/data/cred"
type: Opaque
stringData:
  username: <username>
  password: <password>
```
