### ISSUE TITLE
 plugin sidecar failed. Couldn't find cmp-server plugin supporting repository 

### ISSUE THREAD

**Issue by 13567436138** [argoproj-labs/argocd-vault-plugin#498]
**Describe the bug**

**To Reproduce**
### 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
      discover:
        fileName: "./argocd-vault-plugin"
    - name: argocd-vault-plugin-helm-with-args
      generate:
        command: ["sh", "-c"]
        args: ['helm template "$ARGOCD_APP_NAME" -n "$ARGOCD_APP_NAMESPACE" ${ARGOCD_ENV_HELM_ARGS} . | argocd-vault-plugin generate -']
      discover:
        fileName: "./argocd-vault-plugin-helm-with-args"
    - name: argocd-vault-plugin-helm-with-values
      generate:
        command: ["bash", "-c"]
        args: ['helm template "$ARGOCD_APP_NAME" -n "$ARGOCD_APP_NAMESPACE" -f <(echo "$ARGOCD_ENV_HELM_VALUES") . | argocd-vault-plugin generate -']
      discover:
        fileName: "./argocd-vault-plugin-helm-with-values"
    - name: argocd-vault-plugin-kustomize
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-plugin generate -"]
      discover:
        fileName: "./argocd-vault-plugin-kustomize"
```
secret/argocd-vault-plugin/vault-configuration.yaml

kubectl apply -f vault-configuration.yaml -n argocd

```
apiVersion: v1
stringData:
  VAULT_ADDR: http://192.168.229.148:31758
  AVP_AUTH_TYPE: k8s
  AVP_MOUNT_PATH: auth/kubernetes
  AVP_K8S_ROLE: myapp
  AVP_TYPE: vault
  AVP_K8S_TOKEN_PATH: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
```

```
kubectl exec -ti vault-0 -n vault /bin/sh 

vault policy write app app-policy.hcl

[root@mycompany secret]# cat app-policy.hcl 
path "kv/*" {
  capabilities = ["read"]
}

vault auth enable kubernetes

vault write auth/kubernetes/config \
   token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
   kubernetes_host=https://${KUBERNETES_PORT_443_TCP_ADDR}:443 \
   kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt


vault write auth/kubernetes/role/myapp \
   bound_service_account_names=argocd-repo-server \
   bound_service_account_namespaces=argocd \
   policies=app \
   ttl=1024h
   
   
   
   
vault kv put kv/cred username=mark password=123

```

patch.yaml

kubectl patch -n argocd  deploy argocd-repo-server --patch "$(cat patch.yaml)"

```
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-plugin
          subPath: argocd-vault-plugin
        envFrom:
          - secretRef:
              name: vault-configuration
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/argocd-vault-plugin:v1
        imagePullPolicy: IfNotPresent
        command: [sh, -c]
        args:
          - >-
            cp /argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
      automountServiceAccountToken: true
```

secret/argocd-vault-plugin/ap-clusterResourceWhitelist.yaml

kubectl apply -f ap-clusterResourceWhitelist.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: cluster1
    - server: https://192.168.229.156:6443
      namespace: demo
```

secret/app-argocd-vault-plugin-configmap.yaml

kubectl apply -f app-argocd-vault-plugin-configmap.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    namespace: demo
    name: cluster1
  source:
    repoURL: https://gitee.com/hxpgit/argocd.git
    path: demo1/secretManager/argocd-vault-plugin
    targetRevision: HEAD 
    plugin:
      env:
      - name: VAULT_ADDR
        value: http://vault-active.vault.svc:8200
      - name: AVP_AUTH_TYPE
        value: k8s
      - name: AVP_MOUNT_PATH
        value: auth/kubernetes
      - name: AVP_K8S_ROLE
        value: myapp
      - name: AVP_KV_VERSION
        value: "2"
      - name: AVP_TYPE
        value: vault
      - name: AVP_K8S_TOKEN_PATH
        value: /var/run/secrets/kubernetes.io/serviceaccount/token
  project: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

```

```

```
[root@mycompany secret]# argocd app sync app
TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE
2023-04-21T20:58:51-07:00             Secret        demo    example-annotation   Unknown                       

Name:               argocd/app
Project:            project
Server:             cluster1
Namespace:          demo
URL:                https://argocd-server.argocd.svc.cluster.local/applications/app
Repo:               https://gitee.com/hxpgit/argocd.git
Target:             HEAD
Path:               demo1/secretManager/argocd-vault-plugin
SyncWindow:         Sync Allowed
Sync Policy:        Automated (Prune)
Sync Status:        Unknown
Health Status:      Healthy

Operation:          Sync
Sync Revision:      
Phase:              Error
Start:              2023-04-21 20:58:50 -0700 PDT
Finished:           2023-04-21 20:58:51 -0700 PDT
Duration:           1s
Message:            ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. Couldn't find cmp-server plugin supporting repository .demo1/secretManager/argocd-vault-plugin

GROUP  KIND    NAMESPACE  NAME                STATUS   HEALTH  HOOK  MESSAGE
       Secret  demo       example-annotation  Unknown                
FATA[0001] Operation has completed with phase: Error 
```
#### 
**Expected behavior**

**Screenshots/Verbose output**

If you've tried running `argocd-vault-plugin generate` with `--verbose-sensitive-output` to help debug, please include that output here after redacting any secrets.

**Additional context**
