### ISSUE TITLE
Support AWS Secrets Manager binary type

### ISSUE THREAD

**Issue by JBOClara** [argoproj-labs/argocd-vault-plugin#499]
**Is your feature request related to a problem? Please describe.**
When using AWS Secrets Manager Backend, we may need to retrieve binary type. However, the current implementation of genericReplacement needs a key part in the placeholder. We don't want to modify the file `pkg/kube/util.go` but only `pkg/backends/awssecretsmanager.go` 

```
  sample-secret: <path:arn:aws:secretsmanager:<REGION>:<ACCOUNT_NUMBER>:<SECRET_ID>#<key>>
```

**Describe the solution you'd like**
For instance, 
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-example
data:
  sample-secret-string: <path:arn:aws:secretsmanager:<REGION>:<ACCOUNT_NUMBER>:<SECRET_ID>#<key> | <MODIFIER>> # AWS Secret of string type can have a key
  sample-secret-binary: <path:arn:aws:secretsmanager:<REGION>:<ACCOUNT_NUMBER>:<SECRET_ID>> # AWS Secret of binary type can't have a key
type: Opaque
```
AWS Secret of string type can be declared as a key/value and the key is used in the placeholder `#<key>`. For AWS Secret of binary type, we can define a key.

The output of `argocd-vault-plugin generate ...` for this example, will be partially replaced since there is not retrieval of secrets for placeholder without key.
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-example
data:
  sample-secret-string: UFJPSkVUU0FLREtEU0xTS0RES0NOSkRLREtEQ05OQ05OS1BaUFoK
  sample-secret-binary: <path:arn:aws:secretsmanager:<REGION>:<ACCOUNT_NUMBER>:<SECRET_ID>>
type: Opaque
```

**Describe alternatives you've considered**
I was not able to consider alternatives
