### ISSUE TITLE
Argocd-vault-plugin via sidecar with kustomize not working

### ISSUE THREAD

**Issue by midhunkrishnakv** [argoproj-labs/argocd-vault-plugin#504]
**Installing argocd-vault-plugin via sidecar with Kustomize not working as expected**

I'm running argocd v2.6.7 installed.

Since using avp via configmap is deprecated since argocd v2.4, I decided to adopt the change and move to **argocd-vault-plugin sidecar with kustomize**.

So I went ahead and modified the configmap, removed the avp plugin from the configmap and added the new sidecar with kustomize configuration following this example : https://github.com/argoproj-labs/argocd-vault-plugin/tree/main/manifests/cmp-sidecar.

Pushed the changes to the repository and as soon as argocd triggered a sync, it now shows argocd is out of sync and any resources when I try to sync it doesn't update the resources, plus if I see each of the resources diff it shows that is OutOfSync (requires pruning). 

```
SyncError
Skipping sync attempt to eca7b13fc565117dd10fb2050bf2e93cacbc1db9: auto-sync will wipe out all resources
```

When trying to see the diff, I can only see the live manifest and it doesn't show the desired manifest, which it will render by fully removing argocd and other apps.

I did a force sync and indeed argocd was removed, I deployed again argocd and all the applications just to find that the problem is still there, the only difference I can find is the avp sidecar with kustomize but not sure what else can be.

**Comment by werne2j** [comment]
I think you’d be better to ask this question in the Argo CD repo https://github.com/argoproj/argo-cd. There seems to be something wrong with your Argo CD setup and less of an issue with AVP itself.

**Comment by joshuabaird** [comment]
@midhunkrishnakv I'm having this exact same issue.  Did you ever figure it out?

**Comment by apetrosyan1613** [comment]
The same issue

**Comment by joshuabaird** [comment]
You probably have a CMP problem that is returning no data thus making Argo want to remove all resources.  Check the repo-server logs for more details.

**Comment by apetrosyan1613** [comment]
@everops-matt Hmmm
It helped me: update to 5.34.1

I use a helm chart for deployment:

```yaml
configs:
   secret:
    extra:
      VAULT_ADDR: <external_url>
      VAULT_CACERT: /etc/ssl/certs/ca-certificates.crt
      AVP_TYPE: vault
      AVP_AUTH_TYPE: approle
      AVP_ROLE_ID:
      AVP_SECRET_ID: 
  cmp:
    create: true
    plugins:
      argocd-vault-plugin:
        generate:
          command: ["argocd-vault-plugin"]
          args: ["generate -s argocd:argocd-secret", "./"]
      argocd-vault-plugin-helm:
        init:
          command:
            - "sh"
            - "-c"
            - |
              helm repo add argo https://argoproj.github.io/argo-helm
              helm dependency build 
        generate:
          command:
            - sh
            - "-c"
            - |
              helm template $ARGOCD_APP_NAME --include-crds . |
              argocd-vault-plugin generate -
      argocd-vault-plugin-kustomize:
        generate:
          command: ["sh", "-c"]
          args: ["kustomize build . | argocd-vault-plugin generate -s argocd:argocd-secret -"]

  cm:
    kustomize.buildOptions: --enable-helm

  extraContainers: 
    - name: argocd-vault-plugin
      command:
        - "/var/run/argocd/argocd-cmp-server"
      image: quay.io/argoproj/argocd:v2.7.2
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: argocd-vault-plugin.yaml
          name: argocd-cmp-cm
        - mountPath: /tmp
          name: cmp-tmp
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin
        - name: custom-tools
          subPath: kustomize
          mountPath: /usr/local/bin/kustomize
        - name: ca-certificates
          mountPath: /etc/ssl/certs/
    - name: argocd-vault-plugin-helm
      command:
        - "/var/run/argocd/argocd-cmp-server"
      image: quay.io/argoproj/argocd:v2.7.2
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: argocd-vault-plugin-helm.yaml
          name: argocd-cmp-cm
        - mountPath: /tmp
          name: cmp-tmp
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin
        - name: ca-certificates
          mountPath: /etc/ssl/certs/
    - name: argocd-vault-plugin-kustomize
      command:
        - "/var/run/argocd/argocd-cmp-server"
      image: quay.io/argoproj/argocd:v2.7.2
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: argocd-vault-plugin-kustomize.yaml
          name: argocd-cmp-cm
        - mountPath: /tmp
          name: cmp-tmp
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin
        - name: custom-tools
          subPath: kustomize
          mountPath: /usr/local/bin/kustomize
        - name: custom-tools
          subPath: helm
          mountPath: /usr/local/bin/helm
        - name: ca-certificates
          mountPath: /etc/ssl/certs/

  initContainers:
  - name: download-tools
    image: alpine:3
    command: [sh, -c]
    env:
      - name: AVP_VERSION
        value: "1.14.0"
    args:
        - >-
          wget -O argocd-vault-plugin
          https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/ &&
          wget -qO kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.7/kustomize_v4.5.7_linux_amd64.tar.gz && 
          tar -xvzf  kustomize.tar.gz &&
          chmod +x kustomize &&
          mv kustomize /custom-tools/ &&
          wget https://get.helm.sh/helm-v3.11.1-linux-amd64.tar.gz -O - | tar xz && mv linux-amd64/helm /custom-tools/ && chmod +x /custom-tools/helm
    volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
  - name: download-ca-certificates
    image: alpine:3
    command: [sh, -c]
    args:
      - >-
        apk --no-cache add ca-certificates &&
        cp /etc/ssl/certs/ca-certificates.crt /ca-certificates
    volumeMounts:
      - mountPath: /ca-certificates
        name: ca-certificates
  volumeMounts:
  - mountPath: /custom-tools
    name: custom-tools
  volumes:
  - name: argocd-cmp-cm
    configMap:
      name: argocd-cmp-cm
  - name: cmp-tmp
    emptyDir: {}
  - name: custom-tools
    emptyDir: {}
  - name: ca-certificates
    emptyDir: {}
```
