### ISSUE TITLE
Error: Chart.yaml file is missing Error: No manifests Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile)

### ISSUE THREAD

**Issue by alexvaque** [argoproj-labs/argocd-vault-plugin#514]
**Describe the bug**

Hi, How are you ?  

I got the following
``` 
rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `bash -c "helm template $ARGOCD_APP_NAME ${helm_args} -n $ARGOCD_APP_NAMESPACE . |\\\nargocd-vault-plugin generate -s argocd-stg:argocd-vault-plugin-credentials -\n"` failed exit status 1: Error: Chart.yaml file is missing Error: No manifests Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>

``` 

I was following the good instructions of argo-vault-plugin installation from here:
https://luafanti.medium.com/injecting-secrets-from-vault-into-helm-charts-with-argocd-43fc1df57e74
https://github.com/luafanti/arogcd-vault-plugin-with-helm

and I did someting EXTRA ... I added these 2 lines in argo helm chart ( I think that tutorial forgot these 2 lines )
```

  envFrom:
   - secretRef:
       name: argocd-vault-plugin-credentials

```

I got the following error in around 40% of my Argo APPs deployed, the other 60% are working

` 
rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `bash -c "helm template $ARGOCD_APP_NAME ${helm_args} -n $ARGOCD_APP_NAMESPACE . |\\\nargocd-vault-plugin generate -s argocd-stg:argocd-vault-plugin-credentials -\n"` failed exit status 1: Error: Chart.yaml file is missing Error: No manifests Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>

` 

**To Reproduce**

I tried three different config-maps (argocd-vault-plugin-cmp.yaml) and I added in the argo helm chart installation the Secret ref and I got the ENV variables in argocd-repo-server needed to connect to VAULT 

```


apiVersion: v1
--
data:
plugin.yaml: \|
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
name: argocd-vault-plugin-helm
spec:
allowConcurrency: true
discover:
find:
command:
- sh
- "-c"
- "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
generate:
command:
- sh
- "-c"
- \|
helm template $ARGOCD_APP_NAME --include-crds . \|
argocd-vault-plugin generate -
lockRepo: false


```

```


apiVersion: v1
--
kind: ConfigMap
metadata:
name: cmp-plugin
data:
plugin.yaml: \|
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
name: argocd-vault-plugin-helm
spec:
allowConcurrency: true
discover:
find:
command:
- sh
- "-c"
- "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
init:
command:
- bash
- "-c"
- \|
helm repo add bitnami https://charts.bitnami.com/bitnami
helm dependency build
generate:
command:
- bash
- "-c"
- \|
helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo "$ARGOCD_ENV_HELM_VALUES") . \|
argocd-vault-plugin generate -s argocd-stg:argocd-vault-plugin-credentials -
lockRepo: false


```

```


apiVersion: v1
--
data:
plugin.yaml: \|
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
name: argocd-vault-plugin-helm
spec:
allowConcurrency: true
# Note: this command is run _before_ any Helm templating is done, therefore the logic is to check
# if this looks like a Helm chart and if so return 0
discover:
find:
command:
- sh
- "-c"
- "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
 
 
# Note: Due to https://github.com/argoproj/argo-cd/pull/9319, env vars from the Application manifest are prefixed with `ARGOCD_ENV`
generate:
command:
- sh
- "-c"
- \|
helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . \|
argocd-vault-plugin generate -
 
init:
command:
- sh
- "-c"
- \|
export HELM_CACHE_HOME=/tmp/cache &&
export HELM_CONFIG_HOME=/tmp/config &&
export HELM_DATA_HOME=/tmp/data &&
helm repo add bitnami https://charts.bitnami.com/bitnami &&
(helm dependency build \|\| true)
lockRepo: false
kind: ConfigMap
```

In other ISSUES I saw that you debug the AVP inside the SIDECAR container running  `env|grep AVP`

```
➜  argocd git:(dev) k exec argocd-repo-server-5b98fc8db5-s9jsq -it /bin/sh 
Defaulted container "repo-server" out of: repo-server, avp-helm, copyutil (init), download-tools (init)
$ env |grep AVP
AVP_TYPE=vault
AVP_AUTH_TYPE=approle
AVP_SECRET_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXX
AVP_ROLE_ID=XXXXXXXXXXXXXX
```
note: avp-helm sidecar does not have the variables like the repo-server sidecar

HELM INSTALLATION ARGO

```



## Repo Server
repoServer:
  name: repo-server
  replicas: 2
  # argo vault plugin
  imagePullSecrets: []
  extraArgs: []
  env: []
  envFrom:
   - secretRef:
       name: argocd-vault-plugin-credentials
  rbac:
    - verbs:
        - get
        - list
        - watch
      apiGroups:
        - ''
      resources:
        - secrets
        - configmaps
  initContainers:
    - name: download-tools
      image: registry.access.redhat.com/ubi8
      env:
        - name: AVP_VERSION
          value: 1.11.0
      command: [sh, -c]
      args:
        - >-
          curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  extraContainers:
    - name: avp-helm
      command: [/var/run/argocd/argocd-cmp-server]
      image: quay.io/argoproj/argocd:v2.6.8
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /home/argocd/cmp-server/config
          name: cmp-plugin
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin
  volumes:
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
    - name: custom-tools
      emptyDir: {}
    - name: tmp-dir
      emptyDir: {}
  ## end argo vault plugin


```

 **argocd-vault-plugin-credentials.yaml** 
```
kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
type: Opaque
stringData:
  AVP_TYPE: "vault"
  VAULT_ADDR: "https://XXX.vault.XXX.com"
  AVP_AUTH_TYPE: "approle"
  AVP_ROLE_ID: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  AVP_SECRET_ID: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```

**Expected behavior**
After argo-vault-plugin Argo can install only 60% of my apps . Before argo-vault-plugin everything works fine. Thanks

**Comment by alexvaque** [comment]
I think that I got it 

following the previous tutorials examples
https://piotrminkowski.com/2022/08/08/manage-secrets-on-kubernetes-with-argocd-and-vault/
https://luafanti.medium.com/injecting-secrets-from-vault-into-helm-charts-with-argocd-43fc1df57e74


plus the official documentation with the new updates in the argo-vault-plugin
https://argocd-vault-plugin.readthedocs.io/en/stable/installation/#initcontainer-and-configuration-via-sidecar

```  # argo vault plugin
  envFrom:
   - secretRef:
       name: argocd-vault-plugin-credentials
  rbac:
    - verbs:
        - get
        - list
        - watch
      apiGroups:
        - ''
      resources:
        - secrets
        - configmaps
  initContainers:
    - name: download-tools
      image: registry.access.redhat.com/ubi8
      env:
        - name: AVP_VERSION
          value: 1.11.0
      command: [sh, -c]
      args:
        - >-
          curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  extraContainers:
    - name: avp
      command: [/var/run/argocd/argocd-cmp-server]
      image: registry.access.redhat.com/ubi8
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp
        # Register plugins into sidecar
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: avp.yaml
          name: cmp-plugin
        # Important: Mount tools into $PATH
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin
  volumes:
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
    - name: custom-tools
      emptyDir: {}
  ## end argo vault plugin


```


and the new configmap 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "."
      lockRepo: false
---

```

Now all the argo apps are in GREEN
