### ISSUE TITLE
Deployment of apps in different namespace

### ISSUE THREAD

**Issue by aleksandarilic96** [argoproj-labs/argocd-vault-plugin#524]
Hello everyone,

I have been testing argocd vault helm plugin and was able to configure it and make it work in the argocd namespace. But as soon as I try to deploy the same app that works in argocd namespace to some other its falling with this error. The only change is namespace so I'm not sure what I missed in docs 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: infra/helm
    repoURL: 'https://github.com/luafanti/spring-boot-debug-app'
    targetRevision: main
    plugin:
      env:
      - name: helm_values
        value: |
          serviceAccount:
            create: true
          image:
            repository: luafanti/spring-boot-debug-app
            tag: main
            pullPolicy: IfNotPresent
          replicaCount: 1
          resources:
            memoryRequest: 256Mi
            memoryLimit: 512Mi
            cpuRequest: 500m
            cpuLimit: 1 
          probes:
            liveness:
              initialDelaySeconds: 15
              path: /actuator/health/liveness
              failureThreshold: 3
              successThreshold: 1
              timeoutSeconds: 3
              periodSeconds: 5
            readiness:
              initialDelaySeconds: 15
              path: /actuator/health/readiness
              failureThreshold: 3
              successThreshold: 1
              timeoutSeconds: 3
              periodSeconds: 5
          ports:
            http:
              name: http
              value: 8080
            management:
              name: management
              value: 8081
          envs:
            - name: VAULT_SECRET_USER
              value: <path:kv-v2/data/demo#user>
            - name: VAULT_SECRET_PASSWORD
              value: <path:kv-v2/data/demo#password>
          log:
            level:
              spring: "info"
              service: "info"
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

Unable to create application: application spec for demo is invalid: InvalidSpecError: Unable to generate manifests in infra/helm: rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `bash -c "helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo \"$ARGOCD_ENV_helm_values\") . |\nargocd-vault-plugin generate -s argocd:argocd-vault-plugin-credentials --verbose-sensitive-output -\n"` failed exit status 1: 2023/06/24 22:30:24 reading configuration from secret argocd:argocd-vault-plugin-credentials 2023/06/24 22:30:24 parsed secret name as argocd-vault-plugin-credentials from namespace argocd 2023/06/24 22:30:24 Setting VAULT_ADDR to https://vault.homelab.lan for backend SDK 2023/06/24 22:30:24 Setting VAULT_SKIP_VERIFY to TRUE for backend SDK 2023/06/24 22:30:24 reading configuration from environment, overriding any previous settings 2023/06/24 22:30:24 AVP configured with the following settings: 2023/06/24 22:30:24 avp_kv_version: 2 2023/06/24 22:30:24 helm_values: serviceAccount: create: true image: repository: luafanti/spring-boot-debug-app tag: main pullPolicy: IfNotPresent replicaCount: 1 resources: memoryRequest: 256Mi memoryLimit: 512Mi cpuRequest: 500m cpuLimit: 1 probes: liveness: initialDelaySeconds: 15 path: /actuator/health/liveness failureThreshold: 3 successThreshold: 1 timeoutSeconds: 3 periodSeconds: 5 readiness: initialDelaySeconds: 15 path: /actuator/health/readiness failureThreshold: 3 successThreshold: 1 timeoutSeconds: 3 periodSeconds: 5 ports: http: name: http value: 8080 management: name: management value: 8081 envs: - name: VAULT_SECRET_USER value: <path:kv-v2/data/demo#user> - name: VAULT_SECRET_PASSWORD value: <path:kv-v2/data/demo#password> log: level: spring: "info" service: "info" 2023/06/24 22:30:24 vault_skip_verify: TRUE 2023/06/24 22:30:24 avp_auth_type: approle 2023/06/24 22:30:24 avp_role_id: 926662-1d5f-7819-7701-de48c1c9d6e9 2023/06/24 22:30:24 avp_secret_id: db040aa4587-f2b1-801a-45f4-a485a0c0132e 2023/06/24 22:30:24 avp_type: vault 2023/06/24 22:30:24 vault_addr: https://vault.homelab.lan 2023/06/24 22:30:24 Hashicorp Vault authenticating with role ID 9285d602-1d5f-7819-7701-de48c1c9d6e9 and secret ID db040a87-f2b1-809a-45f4-a485a0c0132e 

**Error: invalid character '<' looking for beginning of value Usage:** argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name> --verbose-sensitive-output enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr
