### ISSUE TITLE
The error says "Error: Could not find file <path to the encrypted file>" but actual error is that I didn't specify `SOPS_AGE_KEY_FILE` variable

### ISSUE THREAD

**Issue by ArtemShevelyukhin** [argoproj-labs/argocd-vault-plugin#532]
**Describe the bug**
The error says "Error: Could not find file <path to the encrypted file>" but actual error is that I didn't specify `SOPS_AGE_KEY_FILE` variable

**To Reproduce**

**Expected behavior**
The error says "`SOPS_AGE_KEY_FILE` variable is missing, please specify it"

**Screenshots/Verbose output**

If you've tried running `argocd-vault-plugin generate` with `--verbose-sensitive-output` to help debug, please include that output here after redacting any secrets.

**Additional context**

**Comment by cpdeethree** [comment]
I had this same problem, but also a second one. The second problem is that you need to ensure that the path referenced in your dummy injected secret is the relative path from where your application is configured, not the fully qualified path

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: storj-s3-secret
  namespace: seaweedfs
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
  annotations:
    avp.kubernetes.io/path: "s3-creds.enc" # NOTE: MAKE SURE THIS IS RELATIVE TO YOUR APPLICATION PATH, NOT FQ PATH IE NOT path/from/root/of/repo/s3-creds.enc
type: Opaque
stringData:
  seaweedfs_s3_config: <seaweedfs_s3_config>
```

Lastly, I found out from another issue, that s3-creds.enc, as you have in your example, cannot end in yaml, or avp/argo interprets it as a kubernetes manifest and tries to apply it.
