### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by barth12** [argoproj-labs/argocd-vault-plugin#538]
**Describe the bug**
"exec format error" when trying to run argocd-vault-plugin as a sidecar.

**To Reproduce**
Here's my Helm config values:

```
redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
  serviceAccount:
    automountServiceAccountToken: true
  volumes:
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
    - name: custom-tools
      emptyDir: {}
    - name: vault-server-tls-secret
      secret:
        secretName: vault-server-tls-secret
  initContainers:
    - name: download-tools
      image: registry.access.redhat.com/ubi8
      env:
        - name: AVP_VERSION
          value: ${local.argo_cd_vault_plugin_version}
      command: [sh, -c]
      args:
        - >-
          curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  extraContainers:
    - name: avp
      command: [/var/run/argocd/argocd-cmp-server]
      image: quay.io/argoproj/argocd:v${local.argo_cd_version}
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp

        # Register plugins into sidecar
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: avp.yaml
          name: cmp-plugin

        # Important: Mount tools into $PATH
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin

        # mounted Vault TLS CA CERT
        - name: vault-server-tls-secret
          mountPath: "/vault/tls"
      envFrom:
       - secretRef:
           name: argocd-vault-plugin-credentials

applicationSet:
  replicaCount: 2
```

And my config map:

```
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argocd-vault-plugin
spec:
  allowConcurrency: true
  discover:
    find:
      command:
        - sh
        - "-c"
        - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
  generate:
    command:
      - argocd-vault-plugin
      - generate
      - "."
  lockRepo: false

```

My Application:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: test
  source:
    path: argocd
    repoURL: git@github.com:test/test.git
    targetRevision: master
    plugin:
      name: argocd-vault-plugin

```

**Expected behavior**
It should not result in error:

`rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: fork/exec /usr/local/bin/argocd-vault-plugin: exec format error`

**Additional context**
Version: 2.7.3
