### ISSUE TITLE
Question: Why cant we specify the plugin name?

### ISSUE THREAD

**Issue by gvu0110** [argoproj-labs/argocd-vault-plugin#540]
I'm using `argocd-vault-plugin` as sidecar container. In the official ArgoCD docs, it's saying we can specify only a particular plugin to be used by using `name: <metadata.name>-<spec.version>`
https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#using-a-config-management-plugin-with-an-application

My `cmp-plugin` ConfigMap looks like this:
```yaml
data:
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      version: v1.9.0
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "."
      lockRepo: false
```
My ArgoCD application manifest looks like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-secrets-controller
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/secrets
    repoURL: git@github.com:foo/bar.git
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-v1.9.0
```
And I got the error: `Unable to create application: application spec for dev-secrets-controller is invalid: InvalidSpecError: Unable to generate manifests in apps/secrets: rpc error: code = Unknown desc = Manifest generation error (cached): config management plugin not supported. plugin name argocd-vault-plugin-v1.9.0`

By using `plugin: {}`, it works perfectly. I do see you mention in the [argocd-vault-plugin docs](https://argocd-vault-plugin.readthedocs.io/en/stable/usage/) that `# Don't include this if installing via sidecar`.

But why? Can you please explain?
