### ISSUE TITLE
Use of AVP with helm OCI registry and multiple sources

### ISSUE THREAD

**Issue by Thiryn** [argoproj-labs/argocd-vault-plugin#541]
**Describe the bug**
When I use AVP with a helm registry, AVP does not trigger on the values file.

**To Reproduce**
Using sidecar AVP. Configuration works fine with raw yaml.
Using the following example source:
```yaml
  sources:
    - repoURL: 'https://github.com/me/my-private-repo'
      path: path/to/values
      targetRevision: master
      ref: values-repo
    - chart: postgresql
      repoURL: registry-1.docker.io/bitnamicharts # an oci chart registry
      targetRevision: 16.0.3
      helm:
        releaseName: postgresql
        valueFiles:
          - $values-repo/path/to/values/values.yaml
```

The `$values-repo/path/to/values/values.yaml` contains a sample values file with some vault secret to replace, for example:
```
global:
  postgresql:
    auth:
      postgresPassword: <path:postgres/auth#password>
```

This will trigger AVP on the `values-repo` source, not on the `helm` source. This will trigger the replace as the condition `find . -name 'Chart.yaml' && find . -name 'values.yaml'` set in the config is met, the generation will ensue `helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . | argocd-vault-plugin generate -s my-secret -`

I assume this isn't enough as the generation ends up with the following logs:

```txt
time="" level=info msg="Generating manifests with no request-level timeout"
time="" level=info msg="sh -c \"helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . |\
argocd-vault-plugin generate -s my-secret -\
\"" dir=/tmp/_cmp_server/.../path/to/values execID=46470
time="2023-08-23T08:55:02Z" level=warning msg="Plugin command returned zero output" command="{[sh -c helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . |
argocd-vault-plugin generate -s my-secret -] []}" stderr="Error: Chart.yaml file is missing"
```

**Expected behavior**
AVP replaces secrets when using multiple sources

**Additional context**
I tried other solutions, like using inline values directly in the `helm` source (which I would like to avoid anyway), but AVP isn't even triggered for remote OCI sources.
