### ISSUE TITLE
Question: setup problem with avp + helm

### ISSUE THREAD

**Issue by ryan-dyer-sp** [argoproj-labs/argocd-vault-plugin#542]
I'm trying to setup avp to be used with a helm chart.  I have a values YAML file containing `key: "<path:ns:secret#key>"` I pass this in to a ConfigMap which in turn is generating the same format.  If i take that file and put it in the argocd-repo-server or the plugin sidecar and run avp against it, it renders as desired.  But not through the standard argo application helm chart sync.  So I'm assuming I've missed something in my setup.

The entire argocd is installed via the argo-cd helm chart.  For my cmp-cm config I have
```
> k get cm argocd-cmp-cm -o yaml
apiVersion: v1
data:
  argocd-vault-plugin-helm.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
          - sh
          - -c
          - find . -name 'Chart.yaml' && find . -name 'values.yaml'
      generate:
        command:
        - sh
        - -c
        - |
          helm template $ARGOCD_APP_NAME --include-crds . |
          AVP_TYPE=kubernetessecret  argocd-vault-plugin generate -
      lockRepo: false
kind: ConfigMap
```

The sidecar is defined via:
```
  extraContainers:
  - name: argocd-vault-plugin-helm
    command: [/var/run/argocd/argocd-cmp-server]
    image: registry.access.redhat.com/ubi8
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
    volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins
      - mountPath: /tmp
        name: tmp
      # Register plugins into sidecar
      - mountPath: /home/argocd/cmp-server/config/plugin.yaml
        subPath: argocd-vault-plugin-helm.yaml
        name: argocd-cmp-cm
      # Important: Mount tools into $PATH
      - name: plugins
        subPath: argocd-vault-plugin
        mountPath: /usr/local/bin/argocd-vault-plugin
```

Is there something else I'm missing?  Thanks!
