### ISSUE TITLE
ENV variable from Application manifest not available in AVP sidecar container

### ISSUE THREAD

**Issue by michizubi-SRF** [argoproj-labs/argocd-vault-plugin#545]
**Describe the bug**
ENV variable defined in Application manifest is not available in the sidecar container

**To Reproduce**
We configured the AVP with the sidecar method as described in the docs (https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#using-environment-variables-in-your-plugin). Since we need extra arguments for the helm command we defined the variable in the application manifest as follows:

```
spec:
  project: default
  source:
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f values.yaml -f values-{{ .Values.phase | default "dev" }}.yaml
```
According to the docs the variable "HELM_ARGS" should be available to the sidecar container, however, this is not the case.
If we define the variable in the spec for the sidecar as follows, the ENV var is available:

```
extraContainers:
- name: argocd-vault-plugin
  command: [/var/run/argocd/argocd-cmp-server]
...
      env:
      - name: HELM_ARGS
        value: -f values.yaml -f values-dev.yaml
```

**Expected behavior**
ENV variable should be available to the container as described in the docs
