### ISSUE TITLE
Question: Debug argocd-vault-plugin

### ISSUE THREAD

**Issue by Khuman2** [argoproj-labs/argocd-vault-plugin#547]
Could you help me with argocd-vault-plugin debugging? 
I try to get secrets from Google Secret Manager. I checked permissions from the test pod that I ran with the same ServiceAccount by gcloud command. My service account permissions work fine!
I tried to debug `argocd-vault-plugin generate test.yaml` command inside the pod and get an error:
```
Error: Replace: could not replace all placeholders in Template:
replaceString: missing Vault value for placeholder password in string password: <password>
```
test.yaml:
```yaml
---
kind: Secret
apiVersion: v1
metadata:
  name: testsecret
  annotations:
    avp.kubernetes.io/path: projects/<project id>/secrets/testsecret
type: Opaque
data:
  password: <password>
```
I set **AVP_TYPE=gcpsecretmanager** also.
How can I get more info about the issue?
Thanks for the advice!
