### ISSUE TITLE
Support same configurations as helm source

### ISSUE THREAD

**Issue by abirsigron** [argoproj-labs/argocd-vault-plugin#562]
TLDR
Migrating the argocd-application template from helm source to argocd-vault-plugin source is complicated.
With the feature I suggest here it should be much easier:

We are currently using helm source for our argo applications which look like:
```
  source:
    helm:
      parameters:
        - name: globalValues.region
          value: us-east-1
      valueFiles:
        - values/test.yaml
        - values/actions-runner-controller.yaml
      skipCrds: false
```

In order to use the plugin we need to pass env variable with the relevant helm arguments:
```
 source:
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: "-f values/test.yaml -f values/actions-runner-controller.yaml --set globalValues.region=us-east-1"
```

I think it will be helpful and much more clear if argocd-vault-plugin will support the same parameters as the helm source.
For example:
```
  source:
    plugin:
      name: argocd-vault-plugin-helm
      parameters:
        - name: globalValues.region
          value: us-east-1
      valueFiles:
        - values/test.yaml
        - values/actions-runner-controller.yaml
      skipCrds: false
```
