### ISSUE TITLE
Re-implementing the Helm CMP - Issues and Documentation Proposal

### ISSUE THREAD

**Issue by maxnitze** [argoproj-labs/argocd-vault-plugin#566]
Hey everyone,

I took a lot of time and searching through the docs and a lot of issue here on GitHub to re-implement the ArgoCD Helm CMP logic with avp.

I still have some open issues, but once I fixed those, I would really like to share the scripts with the community. Ideally somewhere in the docs of this plugin. Is there a place in this repository for such an example? In the `examples` folder? Also in the docs, maybe?

# My CMP YAML

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: avp-helm
spec:
  allowConcurrency: true
  init:
    command:
      - /bin/sh
      - -c
      - |
        #!/usr/bin/env bash
        set -Eeuo pipefail
        
        # add all repositories from dependencies of this chart
        for REPO_URL in $(helm dependency list | tail -n+2 | tr -s '[:space:]' | cut -f3)
        do
          helm repo add $(echo -n "${REPO_URL}" | base64) "${REPO_URL}"
        done
        
        # finally download the charts dependencies
        helm dependency build
  generate:
    command:
      - /bin/sh
      - -c
      - |
        #!/usr/bin/env bash
        set -Eeuo pipefail
        
        # parse parameters from plugin config block in application resource
        # https://github.com/argoproj/argo-cd/blob/master/docs/proposals/parameterized-config-management-plugins.md#how-will-the-cmp-know-what-parameter-values-are-set
        HELM_RELEASE_NAME=$(echo "${ARGOCD_APP_PARAMETERS}" | yq -r eval '.[] | select(.name == "releaseName") | (.string // "${ARGOCD_APP_NAME}") | envsubst | trim')
        HELM_VALUE_FILES=$(echo "${ARGOCD_APP_PARAMETERS}" | yq -r eval '.[] | select(.name == "valueFiles") | .array | map("--values " + .) | join(" ") | trim')
        
        HELM_VALUES=$(echo "${ARGOCD_APP_PARAMETERS}" | yq -r eval '.[] | select(.name == "values") | .string | envsubst | trim')
        if [ ! -z "${HELM_VALUES}" ]; then
          echo "${HELM_VALUES}" > /tmp/${ARGOCD_APP_NAMESPACE}-${ARGOCD_APP_NAME}-values.yaml
          HELM_VALUE_FILES="${HELM_VALUE_FILES} --values /tmp/${ARGOCD_APP_NAMESPACE}-${ARGOCD_APP_NAME}-values.yaml"
        fi
        
        HELM_VALUES_OBJECT=$(echo "${ARGOCD_APP_PARAMETERS}" | yq -r -P eval '.[] | select(.name == "valuesObject") | .map | . |= (.. | select(. | type == "!!str") |= envsubst)')
        if [ ! -z "${HELM_VALUES_OBJECT}" ]; then
          echo "${HELM_VALUES_OBJECT}" > /tmp/${ARGOCD_APP_NAMESPACE}-${ARGOCD_APP_NAME}-values-object.yaml
          HELM_VALUE_FILES="${HELM_VALUE_FILES} --values /tmp/${ARGOCD_APP_NAMESPACE}-${ARGOCD_APP_NAME}-values-object.yaml"
        fi
        
        HELM_PARAMETERS=$(echo "${ARGOCD_APP_PARAMETERS}" | yq -r eval '.[] | select(.name == "parameters") | .array | map("--set " + (. | envsubst)) | join(" ") | trim')
        HELM_EXTRA_PARAMETERS=""
        if [ "${PARAM_PASSCREDENTIALS:-false}" == "true" ]; then
          HELM_EXTRA_PARAMETERS="${HELM_EXTRA_PARAMETERS} --pass-credentials"
        fi
        if [ "${PARAM_SKIPCRDS:-false}" == "true" ]; then
          HELM_EXTRA_PARAMETERS="${HELM_EXTRA_PARAMETERS} --skip-crds"
        fi
        
        helm template ${HELM_RELEASE_NAME} \
          --namespace ${ARGOCD_APP_NAMESPACE} \
          ${HELM_VALUE_FILES} \
          ${HELM_PARAMETERS} \
          ${HELM_EXTRA_PARAMETERS} \
          ./ |
        argocd-vault-plugin generate - -c /run/secrets/vault-configuration/config.yaml
  lockRepo: false
```

## Prerequisites

* needs `helm` and `yq` installed
* works with image `alpine/helm:3.12.3`, for example

## Features

* adds all repositories of dependencies to Helm in the init command
* makes sure, that all repos are only added once (otherwise adding would fail)
  * has issues with private repos (see Open Issues section)
* can handle all parameters mentioned in https://argo-cd.readthedocs.io/en/stable/user-guide/helm/

## Example Application

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd
  # ...
spec:
  # ...
  source:
    # ...
    plugin:
      name: avp-helm
      parameters:
        - name: releaseName
          string: argocd-avp-test
        - name: valueFiles
          array:
            - values.yaml
            - values.extra.yaml
        - name: parameters
          array:
            - extraValueParameters=overwritten-value-parameters
        - name: values
          string: >-
            extraValueValues: overwritten-value-values
        - name: valuesObject
          map:
            extraValueValuesObject: overwritten-value-values-object
        - name: skipCrds
          string: "true"
        - name: passCredentials
          string: "true"
```

# Open Issues

## `init` command on private repo

Adding all the repositories works quite well until we use our private repository, that needs authentication. ArgoCD knows about that (we added [Repository Credentials Secret](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/declarative-setup.md#repository-credentials)), but my plugin fails, because I don't provide any username and password.

Can I somehow access the credentials from that "Repository Credentials Secret" in my custom CMP? I use the _sidecar method_, if that is of any help.
