### ISSUE TITLE
htpasswd function in helm doesn't work as expected

### ISSUE THREAD

**Issue by fkaksa** [argoproj-labs/argocd-vault-plugin#571]
I'm encountering an issue with the ArgoCD Vault plugin while using Helm with additional arguments settings. The problem arises when I try to utilize the htpasswd function within Helm, and it results in an error message stating "invalid username: user.", which content in the end will be part of the k8s manifest file.

Here is my values.yaml file configuration:

```yaml
oauth:
   username: <path:bla/oauth#username>
   password: <path:bla/oauth#password>
```

In this configuration, placeholders for secrets are correctly replaced. However, when I use the htpasswd function in Helm, I receive the "invalid username: user" error.

To provide additional context, I'm using AWS Vault as a backend, and my username is set to "user," and my password is set to "pass."

Additionally, here is the Secret YAML file which contains htpasswd command:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd
data:
  auth: {{ htpasswd (.Values.oauth).username (.Values.oauth).password | b64enc | quote }}
```

To further clarify, here is the plugin configuration:

```yaml
plugin config:
  avp-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      generate:
        command:
          - sh
          - "-c"
          - |
            helm template --include-crds -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . |
            argocd-vault-plugin generate -
```

**Expected behavior**

Secret should looks like:

```
....
data:
  auth: dXNlcjokMmEkMTAkSTJLUHNMRTZMUE1XUlNOZUFwN0NPdUZMRmxHYUk2aHlESnR4a3JYcGgzcTgwanVDTzF6OG0=
```

**Actual behavior**

```
...
data:
  auth: aW52YWxpZCB1c2VybmFtZTogdXNlcg==
```
