### ISSUE TITLE
<placeholder> are not replaced if spec.source.helm.releaseName is set in arcocd Application

### ISSUE THREAD

**Issue by murand78** [argoproj-labs/argocd-vault-plugin#587]
**Describe the bug**
The secret generated in the application contains the original \<placeholder\> instead of the value taken from Vault if spec.source.helm.releaseName is set in arcocd Application.

**To Reproduce**
Create an ArgoCD application like:

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-avp-plugin
  namespace: argocd
spec:
  destination:
    namespace: test-avp-plugin
    server: https://rancher.yyyyyyyyyy.it/k8s/clusters/c-4ph8q
  project: vault
  source:
    helm:
      releaseName: test-avp-plugin-app  
    path: charts/test-avp
    repoURL: https://bitbucket.org/xxxxxxxxxxxxx/argocd-k8s-application-set.git
    targetRevision: HEAD
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - CreateNamespace=true
```
**Expected behavior**

The secret generated still contains the \<placeholder\> like the yaml rendered by the original helm template
Removing the releaseName like the example below works correctly and the placeholder is replaced by the secret value taken from Vault

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-avp-plugin
  namespace: argocd
spec:
  destination:
    namespace: test-avp-plugin
    server: https://rancher.yyyyyyyyyy.it/k8s/clusters/c-4ph8q
  project: vault
  source:
    path: charts/test-avp
    repoURL: https://bitbucket.org/xxxxxxxxxxxxx/argocd-k8s-application-set.git
    targetRevision: HEAD
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - CreateNamespace=true
```

**Additional context**

ArgoCD v2.9.3
argocd-vault-plugin_1.17.0_linux_amd64
Installation via a sidecar container as specified in https://github.com/argoproj-labs/argocd-vault-plugin/tree/main/manifests/cmp-sidecar 
k8s: RKE v1.24.17 
HashiCorp Vault 1.15.1
