### ISSUE TITLE
argocd plugin vault avp-kustomize broke argocd deployment from argocd autopilot

### ISSUE THREAD

**Issue by rchekhina** [argoproj-labs/argocd-vault-plugin#601]
HI,

I have deployed argocd with autopilot and when I patch the argocd-repo-server deployment to add the avp-kustomize sidecar and after this try to add an application or a project with the argocd-autopilot command all the default apps of the bootstrap, argocd, root, and cluster-resources-in-cluster disappear from the GUI.
I have investigating and the issue is the discover of the sidecar :

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true

      # Note: this command is run _before_ anything is done, therefore the logic is to check
      # if this looks like a Kustomize bundle
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
```
I have change the discover to:

```
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'kustomization.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
```

Can you tell me if there is a better discover for avp-kustomize ?

versions:
- argocd-autopilot: v0.4.17
- argocd: 2.9.3
- argocd-vault-plugin: 1.17.0

Best regards.
