### ISSUE TITLE
helm dependency update with inline helm values file

### ISSUE THREAD

**Issue by foster-rh** [argoproj-labs/argocd-vault-plugin#642]
Hi guys

I am using the following cm plugin config map with my side car to access hashi vault to get secrets for my helm charts.
```
  avp-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
      generate:
        command:
          - bash
          - "-c"
          - |
            helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo "$ARGOCD_ENV_HELM_VALUES") . |
            argocd-vault-plugin generate --verbose-sensitive-output -
      lockRepo: false
```
Its not working obviously as it doesnt do the dependency update - and I cant figure out how I cd down the path to the folder do the dependancy update and then do the helm templating with the inline variables from the argocd application.

I can use a simpler helm chart with no dependancies and no requirements for inline arguements and its working fine.
