### ISSUE TITLE
Issue Deploying Secrets via avp-helm Plugin in Helm Chart

### ISSUE THREAD

**Issue by OriMeyuhas** [argoproj-labs/argocd-vault-plugin#665]
### Description:
The `avp` plugin is working correctly when syncing secrets from Vault. However, when attempting to deploy the manifest using the `avp-helm` plugin within a Helm chart, the chart is not being created. When the `avp-helm` plugin is removed, the Helm chart deploys, but the secret placeholders (e.g., `<AWS_ACCESS_KEY>`) are deployed without syncing with Vault, resulting in the secrets not being injected.
Additionally, I tried using the avp-helm plugin without arguments following the official [AVP Helm guide](https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-helm), but the issue persists.

#### Application Manifest:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/fe-app-main
    repoURL: 'https://github.com/myrepo.git'
    targetRevision: ori
    plugin:
      name: avp-helm
      env:
        - name: HELM_ARGS
          value: '-f values.yaml'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

#### Issue:
- With the `avp-helm` plugin enabled, the Helm chart does not get deployed at all. ArgoCD shows the application as synced and healthy, but no resources are created.

### Image: 
![Screenshot 2024-09-22 at 16 15 36](https://github.com/user-attachments/assets/e2dc0dc3-d45a-43b7-a3ac-df606d59062d)

#### Application Manifest:
```yaml
project: default
source:
  repoURL: 'https://github.com/myrepo.git'
  path: charts/fe-app-main
  targetRevision: ori
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
```

#### Issue:
- Without the `avp-helm` plugin, the chart successfully deploys, but the secrets are not synced with Vault. The placeholders (`<AWS_ACCESS_KEY>`, `<AWS_SECRET_ACCESS_KEY>`) are deployed as-is without the expected Vault values.

### Secret Manifest:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-keys
  annotations:
    avp.kubernetes.io/path: "path/to/secret"
type: Opaque
stringData:
  AWS_ACCESS_KEY: <AWS_ACCESS_KEY>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
```

#### CMP Plugin Configuration:
```yaml
avp:
  allowConcurrency: true
  discover:
    find:
      command:
        - sh
        - "-c"
        - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
  generate:
    command:
      - argocd-vault-plugin
      - generate
      - "."
      - "-s"
      - "avp-conf"
  lockRepo: false

avp-helm:
  allowConcurrency: true
  discover:
    find:
      command:
        - sh
        - "-c"
        - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
  generate:
    command:
      - sh
      - "-c"
      - |
        helm template $ARGOCD_APP_NAME --include-crds -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . |
        argocd-vault-plugin generate -s avp-conf -
  lockRepo: false
```

#### Extra Containers Configuration:
```yaml
- name: avp
  command: [/var/run/argocd/argocd-cmp-server]
  image: registry.access.redhat.com/ubi8
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
  volumeMounts:
    - mountPath: /var/run/argocd
      name: var-files
    - mountPath: /home/argocd/cmp-server/plugins
      name: plugins
    - mountPath: /tmp
      name: cmp-tmp
    - mountPath: /home/argocd/cmp-server/config/plugin.yaml
      subPath: avp.yaml
      name: argocd-cmp-cm
    - name: custom-tools
      subPath: argocd-vault-plugin
      mountPath: /usr/local/bin/argocd-vault-plugin

- name: avp-helm
  command: [/var/run/argocd/argocd-cmp-server]
  image: registry.access.redhat.com/ubi8
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
  volumeMounts:
    - mountPath: /var/run/argocd
      name: var-files
    - mountPath: /home/argocd/cmp-server/plugins
      name: plugins
    - mountPath: /tmp
      name: cmp-tmp
    - mountPath: /home/argocd/cmp-server/config/plugin.yaml
      subPath: avp-helm.yaml
      name: argocd-cmp-cm
    - name: custom-tools
      subPath: argocd-vault-plugin
      mountPath: /usr/local/bin/argocd-vault-plugin
```

#### Init Container Configuration:
```yaml
- name: download-tools
  image: alpine:3.8
  command: [sh, -c]
  env:
    - name: AVP_VERSION
      value: "1.18.1"
  args:
    - >-
      wget -O argocd-vault-plugin
      https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
      chmod +x argocd-vault-plugin &&
      mv argocd-vault-plugin /custom-tools/
  volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools
```

#### Volumes:
```yaml
# -- Additional volumeMounts to the repo server main container
volumeMounts:
  - name: custom-tools
    mountPath: /usr/local/bin/argocd-vault-plugin
    subPath: argocd-vault-plugin

# -- Additional volumes to the repo server pod
volumes:
  - name: custom-tools
    emptyDir: {}
  - name: argocd-cmp-cm
    configMap:
      name: argocd-cmp-cm
  - name: cmp-tmp
    emptyDir: {}
```

Thanks in advance for your help!
