### ISSUE TITLE
Plugin not working with directory recurse enabled

### ISSUE THREAD

**Issue by joaorocha-ceiia** [argoproj-labs/argocd-vault-plugin#685]
**Describe the bug**
While testing the plugin, when applying an argocd application to my cluster, with the directory.recurse to true, the secret placeholder doesn't get replaced by the vault plugin. When I disabled the directory.recurse to false, it immediately started working as expected. I tested with multiple version (1.11.0, 1.16.1 and 1.18.1) and every time I got the same behaviour.

**To Reproduce**
1. Apply this example of a argocd application manifest

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-poc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test-vault
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-vault-plugin
    repoURL: https://github.com/TiagoMorais01/ArgoCD-Vault-Teste.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
```

2. Check the value of the "mysecret" secret, applied on the "vault-poc" namespace

```bash
kubectl get secrets mysecret -n vault-poc -o jsonpath='{.data.PORT}' | base64 -d
```

**Expected behavior**
The secret gets the value of  `<password>` instead of the actual value of the secret from the vault (e.g. 9191 or whatever value you configured on the vault)
