### ISSUE TITLE
ArgoCD Plugin Not Showing

### ISSUE THREAD

**Issue by brandi-devops** [argoproj-labs/argocd-vault-plugin#687]
The plugin is not visible in argocd.
I have deployed ArgoCD using a Helm chart and am using the sidecar pattern. It's a completely fresh installation, and I'm not using Vault, but I do use it for the Helm chart values.
### ERROR
```
argo-cd-argocd-repo-server-86dc7d7bbd-jnmjq repo-server time="2024-12-30T08:40:58Z" level=error msg="Unable to connect to config management plugin service with address /home/argocd/cmp-server/plugins/argocd-vault-plugin-h
elm.sock"
argo-cd-argocd-repo-server-86dc7d7bbd-jnmjq repo-server time="2024-12-30T08:40:58Z" level=error msg="error dialing to cmp-server for plugin argocd-vault-plugin-helm.sock, dial unix /home/argocd/cmp-server/plugins/argocd-v
ault-plugin-helm.sock: connect: no such file or directory" CWE=775 security=2
argo-cd-argocd-repo-server-86dc7d7bbd-jnmjq repo-server time="2024-12-30T08:40:58Z" level=error msg="finished unary call with code Unknown" error="failed to populate plugin app details: failed to detect CMP for app: could
n't find cmp-server plugin with name \"argocd-vault-plugin-helm\" supporting the given repository" grpc.code=Unknown grpc.method=GetAppDetails grpc.service=repository.RepoServerService grpc.start_time="2024-12-30T08:40:53
Z" grpc.time_ms=4912.783 span.kind=server system=grpc
```

### Code:
```yaml
initContainers:
  - command:
      - /bin/cp
      - -n
      - /usr/local/bin/argocd
      - /var/run/argocd/argocd-cmp-server
    image: quay.io/argoproj/argocd:v2.13.2
    imagePullPolicy: IfNotPresent
    name: copyutil
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/argocd
      name: var-files
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-c5mwh
      readOnly: true
  - args:
      - wget -O argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64
        && chmod +x argocd-vault-plugin && mv argocd-vault-plugin /custom-tools/
    command:
      - sh
      - -c
    env:
      - name: AVP_VERSION
        value: 1.12.0
    image: alpine:3.8
    imagePullPolicy: IfNotPresent
    name: download-tools
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-c5mwh
      readOnly: true
```

I have added the init container to the repo-server and confirmed that it downloaded successfully:
```
bash
-rwxr-xr-x 1 root root 69566464 Dec 30 04:57 /usr/local/bin/argocd-vault-plugin
```

### ConfigMap:
```yaml
I also added the configuration to argocd-cm. I understand that the CMP (Config Management Plugins) setting may no longer be needed in the recent versions.
configManagementPlugins: |
  - name: argocd-vault-plugin
    generate:
      command: ["argocd-vault-plugin"]
      args: ["generate", "./"]
  - name: argocd-vault-plugin-helm
    generate:
      command: ["sh", "-c"]
      args: ["helm template . > all.yaml && argocd-vault-plugin generate all.yaml"]
  - name: argocd-vault-plugin-kustomize
    generate:
      command: ["sh", "-c"]
      args: ["kustomize build . > all.yaml && argocd-vault-plugin generate all.yaml"]
```

Issue:
Despite following all of these steps, the ArgoCD Vault plugin does not appear to be visible in ArgoCD.
Can anyone help me figure out what might be wrong or if something is missing from the setup?

![스크린샷 2024-12-30 시간: 17 33 34](https://github.com/user-attachments/assets/d3a2ff80-fe07-451a-b622-9e72b09a4544)
