### ISSUE TITLE
GCP Secret Manager Type can't get secret key If GCP Secret Manager use JSON

### ISSUE THREAD

**Issue by kingbj940429** [argoproj-labs/argocd-vault-plugin#689]
**Is your feature request related to a problem? Please describe.**
If use GCP Secret Manager, It can't parse json data

example,
I have a GCP Secret Manager named `kingbj0429-secret`
and `kingbj0429-secret` has various secrets as json
```json
{
  db-username: admin
  db-password: admin
}
```

like this situatiom, argo-vault-plugin for GCP Secret Manager can't parse `db-password` secret

argo-vault-plugin for GCP Secret Manager get all json data itself.

so I can't use secret with GCP
```yaml
apiVersion: v1
data:
  #-- <path:projects/kingbj0429-447407/secrets/kingbj0429-secret#db-password>
  test: PHBhdGg6cHJvamVjdHMva2luZ2JqMDQyOS00NDc0MDcvc2VjcmV0cy9raW5nYmowNDI5LXNlY3JldCNkYi1wYXNzd29yZD4=
kind: Secret
metadata:
  name: test-secrets
  namespace: arc-system
type: Opaque

```

**Describe the solution you'd like**

![Image](https://github.com/user-attachments/assets/0623d3d2-5258-4df7-a133-9a53fd7e37b9)
this is `gcpsecretmanager.go`'s code

It can only use secret manager name as key
json's key can't be key

so I want to add function for parsing json key like `awssecretmanager.go`'s GetSecrets Function
![Image](https://github.com/user-attachments/assets/ea175703-7e32-4087-8d27-6d0a6cf22d18)

**Describe alternatives you've considered**
maybe a implement is needed

**Additional context**
Can I Pull Request this?

I'll code about this
